// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.31926
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ereg.egov.bg/segment/0009-000025")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ereg.egov.bg/segment/0009-000025", IsNullable = false)]
    public partial class RegisteredErrorsInDocumentContent : InformationObject<RegisteredErrorsInDocumentContent>
    {

        private DocumentTypeURI documentTypeURIField;

        private string documentTypeNameField;

        private List<RegisteredErrorInDocumentContent> registeredErrorsField;

        /// <summary>
        /// RegisteredErrorsInDocumentContent class constructor
        /// </summary>
        public RegisteredErrorsInDocumentContent()
        {
            this.registeredErrorsField = new List<RegisteredErrorInDocumentContent>();
            this.documentTypeURIField = new DocumentTypeURI();
        }

        public DocumentTypeURI DocumentTypeURI
        {
            get
            {
                return this.documentTypeURIField;
            }
            set
            {
                if ((this.documentTypeURIField != null))
                {
                    if ((documentTypeURIField.Equals(value) != true))
                    {
                        this.documentTypeURIField = value;
                        this.OnPropertyChanged("DocumentTypeURI");
                    }
                }
                else
                {
                    this.documentTypeURIField = value;
                    this.OnPropertyChanged("DocumentTypeURI");
                }
            }
        }

        public string DocumentTypeName
        {
            get
            {
                return this.documentTypeNameField;
            }
            set
            {
                if ((this.documentTypeNameField != null))
                {
                    if ((documentTypeNameField.Equals(value) != true))
                    {
                        this.documentTypeNameField = value;
                        this.OnPropertyChanged("DocumentTypeName");
                    }
                }
                else
                {
                    this.documentTypeNameField = value;
                    this.OnPropertyChanged("DocumentTypeName");
                }
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Error", IsNullable = false)]
        public List<RegisteredErrorInDocumentContent> RegisteredErrors
        {
            get
            {
                return this.registeredErrorsField;
            }
            set
            {
                if ((this.registeredErrorsField != null))
                {
                    if ((registeredErrorsField.Equals(value) != true))
                    {
                        this.registeredErrorsField = value;
                        this.OnPropertyChanged("RegisteredErrors");
                    }
                }
                else
                {
                    this.registeredErrorsField = value;
                    this.OnPropertyChanged("RegisteredErrors");
                }
            }
        }
    }
}
