// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ereg.egov.bg/segment/0009-000092")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ereg.egov.bg/segment/0009-000092", IsNullable=true)]
    public partial class ElectronicDocumentXml : InformationObject<ElectronicDocumentXml> {
        
        private DocumentTypeURI documentTypeURIField;
        
        private string documentTypeNameField;
        
        private System.Xml.XmlElement electronicDocumentXmlContentField;
        
        /// <summary>
        /// ElectronicDocumentXml class constructor
        /// </summary>
        public ElectronicDocumentXml() {
            this.documentTypeURIField = new DocumentTypeURI();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DocumentTypeURI DocumentTypeURI {
            get {
                return this.documentTypeURIField;
            }
            set {
                if ((this.documentTypeURIField != null)) {
                    if ((documentTypeURIField.Equals(value) != true)) {
                        this.documentTypeURIField = value;
                        this.OnPropertyChanged("DocumentTypeURI");
                    }
                }
                else {
                    this.documentTypeURIField = value;
                    this.OnPropertyChanged("DocumentTypeURI");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentTypeName {
            get {
                return this.documentTypeNameField;
            }
            set {
                if ((this.documentTypeNameField != null)) {
                    if ((documentTypeNameField.Equals(value) != true)) {
                        this.documentTypeNameField = value;
                        this.OnPropertyChanged("DocumentTypeName");
                    }
                }
                else {
                    this.documentTypeNameField = value;
                    this.OnPropertyChanged("DocumentTypeName");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Xml.XmlElement ElectronicDocumentXmlContent {
            get {
                return this.electronicDocumentXmlContentField;
            }
            set {
                if ((this.electronicDocumentXmlContentField != null)) {
                    if ((electronicDocumentXmlContentField.Equals(value) != true)) {
                        this.electronicDocumentXmlContentField = value;
                        this.OnPropertyChanged("ElectronicDocumentXmlContent");
                    }
                }
                else {
                    this.electronicDocumentXmlContentField = value;
                    this.OnPropertyChanged("ElectronicDocumentXmlContent");
                }
            }
        }
    }
}
