// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.31926
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><CustomUsings>InformationObjects.Nomenclatures</CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using InformationObjects.Nomenclatures;
    using System.IO;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.3.0.31927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ereg.egov.bg/segment/0009-000019")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ereg.egov.bg/segment/0009-000019", IsNullable=false)]
    public partial class ReceiptAcknowledgedMessage : InformationObject<ReceiptAcknowledgedMessage> {
        
        private ElectronicServiceProviderBasicData electronicServiceProviderField;
        
        private DocumentElectronicTransportType transportTypeField;
        
        private bool transportTypeFieldSpecified;
        
        private DocumentURI documentURIField;
        
        private System.DateTime receiptTimeField;
        
        private bool receiptTimeFieldSpecified;
        
        private ReceiptAcknowledgedMessageRegisteredBy registeredByField;
        
        private string caseAccessIdentifierField;
        
        private ElectronicServiceApplicant applicantField;
        
        private DocumentTypeURI documentTypeURIField;
        
        private string documentTypeNameField;
        
        private XMLDigitalSignature signatureField;
        
        /// <summary>
        /// ReceiptAcknowledgedMessage class constructor
        /// </summary>
        public ReceiptAcknowledgedMessage() {
            this.signatureField = new XMLDigitalSignature();
            this.documentTypeURIField = new DocumentTypeURI();
            this.applicantField = new ElectronicServiceApplicant();
            this.registeredByField = new ReceiptAcknowledgedMessageRegisteredBy();
            this.documentURIField = new DocumentURI();
            this.electronicServiceProviderField = new ElectronicServiceProviderBasicData();
        }
        
        public ElectronicServiceProviderBasicData ElectronicServiceProvider {
            get {
                return this.electronicServiceProviderField;
            }
            set {
                if ((this.electronicServiceProviderField != null)) {
                    if ((electronicServiceProviderField.Equals(value) != true)) {
                        this.electronicServiceProviderField = value;
                        this.OnPropertyChanged("ElectronicServiceProvider");
                    }
                }
                else {
                    this.electronicServiceProviderField = value;
                    this.OnPropertyChanged("ElectronicServiceProvider");
                }
            }
        }
        
        public DocumentElectronicTransportType TransportType {
            get {
                return this.transportTypeField;
            }
            set {
                if ((transportTypeField.Equals(value) != true)) {
                    this.transportTypeField = value;
                    this.OnPropertyChanged("TransportType");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransportTypeSpecified {
            get {
                return this.transportTypeFieldSpecified;
            }
            set {
                if ((transportTypeFieldSpecified.Equals(value) != true)) {
                    this.transportTypeFieldSpecified = value;
                    this.OnPropertyChanged("TransportTypeSpecified");
                }
            }
        }
        
        public DocumentURI DocumentURI {
            get {
                return this.documentURIField;
            }
            set {
                if ((this.documentURIField != null)) {
                    if ((documentURIField.Equals(value) != true)) {
                        this.documentURIField = value;
                        this.OnPropertyChanged("DocumentURI");
                    }
                }
                else {
                    this.documentURIField = value;
                    this.OnPropertyChanged("DocumentURI");
                }
            }
        }
        
        public System.DateTime ReceiptTime {
            get {
                return this.receiptTimeField;
            }
            set {
                if ((receiptTimeField.Equals(value) != true)) {
                    this.receiptTimeField = value;
                    this.OnPropertyChanged("ReceiptTime");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceiptTimeSpecified {
            get {
                return this.receiptTimeFieldSpecified;
            }
            set {
                if ((receiptTimeFieldSpecified.Equals(value) != true)) {
                    this.receiptTimeFieldSpecified = value;
                    this.OnPropertyChanged("ReceiptTimeSpecified");
                }
            }
        }
        
        public ReceiptAcknowledgedMessageRegisteredBy RegisteredBy {
            get {
                return this.registeredByField;
            }
            set {
                if ((this.registeredByField != null)) {
                    if ((registeredByField.Equals(value) != true)) {
                        this.registeredByField = value;
                        this.OnPropertyChanged("RegisteredBy");
                    }
                }
                else {
                    this.registeredByField = value;
                    this.OnPropertyChanged("RegisteredBy");
                }
            }
        }
        
        public string CaseAccessIdentifier {
            get {
                return this.caseAccessIdentifierField;
            }
            set {
                if ((this.caseAccessIdentifierField != null)) {
                    if ((caseAccessIdentifierField.Equals(value) != true)) {
                        this.caseAccessIdentifierField = value;
                        this.OnPropertyChanged("CaseAccessIdentifier");
                    }
                }
                else {
                    this.caseAccessIdentifierField = value;
                    this.OnPropertyChanged("CaseAccessIdentifier");
                }
            }
        }
        
        public ElectronicServiceApplicant Applicant {
            get {
                return this.applicantField;
            }
            set {
                if ((this.applicantField != null)) {
                    if ((applicantField.Equals(value) != true)) {
                        this.applicantField = value;
                        this.OnPropertyChanged("Applicant");
                    }
                }
                else {
                    this.applicantField = value;
                    this.OnPropertyChanged("Applicant");
                }
            }
        }
        
        public DocumentTypeURI DocumentTypeURI {
            get {
                return this.documentTypeURIField;
            }
            set {
                if ((this.documentTypeURIField != null)) {
                    if ((documentTypeURIField.Equals(value) != true)) {
                        this.documentTypeURIField = value;
                        this.OnPropertyChanged("DocumentTypeURI");
                    }
                }
                else {
                    this.documentTypeURIField = value;
                    this.OnPropertyChanged("DocumentTypeURI");
                }
            }
        }
        
        public string DocumentTypeName {
            get {
                return this.documentTypeNameField;
            }
            set {
                if ((this.documentTypeNameField != null)) {
                    if ((documentTypeNameField.Equals(value) != true)) {
                        this.documentTypeNameField = value;
                        this.OnPropertyChanged("DocumentTypeName");
                    }
                }
                else {
                    this.documentTypeNameField = value;
                    this.OnPropertyChanged("DocumentTypeName");
                }
            }
        }
        
        public XMLDigitalSignature Signature {
            get {
                return this.signatureField;
            }
            set {
                if ((this.signatureField != null)) {
                    if ((signatureField.Equals(value) != true)) {
                        this.signatureField = value;
                        this.OnPropertyChanged("Signature");
                    }
                }
                else {
                    this.signatureField = value;
                    this.OnPropertyChanged("Signature");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.3.0.31927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ereg.egov.bg/segment/0009-000019")]
    public partial class ReceiptAcknowledgedMessageRegisteredBy : InformationObject<ReceiptAcknowledgedMessageRegisteredBy> {
        
        private object itemField;
        
        [System.Xml.Serialization.XmlElementAttribute("AISURI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Officer", typeof(ReceiptAcknowledgedMessageRegisteredByOfficer))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                if ((this.itemField != null)) {
                    if ((itemField.Equals(value) != true)) {
                        this.itemField = value;
                        this.OnPropertyChanged("Item");
                    }
                }
                else {
                    this.itemField = value;
                    this.OnPropertyChanged("Item");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.3.0.31927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ereg.egov.bg/segment/0009-000019")]
    public partial class ReceiptAcknowledgedMessageRegisteredByOfficer : InformationObject<ReceiptAcknowledgedMessageRegisteredByOfficer> {
        
        private AISUserNames personNamesField;
        
        private string aISUserIdentifierField;
        
        public AISUserNames PersonNames {
            get {
                return this.personNamesField;
            }
            set {
                if ((this.personNamesField != null)) {
                    if ((personNamesField.Equals(value) != true)) {
                        this.personNamesField = value;
                        this.OnPropertyChanged("PersonNames");
                    }
                }
                else {
                    this.personNamesField = value;
                    this.OnPropertyChanged("PersonNames");
                }
            }
        }
        
        public string AISUserIdentifier {
            get {
                return this.aISUserIdentifierField;
            }
            set {
                if ((this.aISUserIdentifierField != null)) {
                    if ((aISUserIdentifierField.Equals(value) != true)) {
                        this.aISUserIdentifierField = value;
                        this.OnPropertyChanged("AISUserIdentifier");
                    }
                }
                else {
                    this.aISUserIdentifierField = value;
                    this.OnPropertyChanged("AISUserIdentifier");
                }
            }
        }
    }
}
