// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ereg.egov.bg/segment/0009-000139")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ereg.egov.bg/segment/0009-000139", IsNullable=true)]
    public partial class AttachedDocument : InformationObject<AttachedDocument> {
        
        private byte[] attachedDocumentFileContentField;
        
        private string attachedDocumentDescriptionField;
        
        private string attachedDocumentUniqueIdentifierField;
        
        private string fileTypeField;
        
        private string attachedDocumentFileNameField;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] AttachedDocumentFileContent {
            get {
                return this.attachedDocumentFileContentField;
            }
            set {
                if ((this.attachedDocumentFileContentField != null)) {
                    if ((attachedDocumentFileContentField.Equals(value) != true)) {
                        this.attachedDocumentFileContentField = value;
                        this.OnPropertyChanged("AttachedDocumentFileContent");
                    }
                }
                else {
                    this.attachedDocumentFileContentField = value;
                    this.OnPropertyChanged("AttachedDocumentFileContent");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AttachedDocumentDescription {
            get {
                return this.attachedDocumentDescriptionField;
            }
            set {
                if ((this.attachedDocumentDescriptionField != null)) {
                    if ((attachedDocumentDescriptionField.Equals(value) != true)) {
                        this.attachedDocumentDescriptionField = value;
                        this.OnPropertyChanged("AttachedDocumentDescription");
                    }
                }
                else {
                    this.attachedDocumentDescriptionField = value;
                    this.OnPropertyChanged("AttachedDocumentDescription");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AttachedDocumentUniqueIdentifier {
            get {
                return this.attachedDocumentUniqueIdentifierField;
            }
            set {
                if ((this.attachedDocumentUniqueIdentifierField != null)) {
                    if ((attachedDocumentUniqueIdentifierField.Equals(value) != true)) {
                        this.attachedDocumentUniqueIdentifierField = value;
                        this.OnPropertyChanged("AttachedDocumentUniqueIdentifier");
                    }
                }
                else {
                    this.attachedDocumentUniqueIdentifierField = value;
                    this.OnPropertyChanged("AttachedDocumentUniqueIdentifier");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                if ((this.fileTypeField != null)) {
                    if ((fileTypeField.Equals(value) != true)) {
                        this.fileTypeField = value;
                        this.OnPropertyChanged("FileType");
                    }
                }
                else {
                    this.fileTypeField = value;
                    this.OnPropertyChanged("FileType");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AttachedDocumentFileName {
            get {
                return this.attachedDocumentFileNameField;
            }
            set {
                if ((this.attachedDocumentFileNameField != null)) {
                    if ((attachedDocumentFileNameField.Equals(value) != true)) {
                        this.attachedDocumentFileNameField = value;
                        this.OnPropertyChanged("AttachedDocumentFileName");
                    }
                }
                else {
                    this.attachedDocumentFileNameField = value;
                    this.OnPropertyChanged("AttachedDocumentFileName");
                }
            }
        }
    }
}
