// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ereg.egov.bg/segment/0009-000011")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ereg.egov.bg/segment/0009-000011", IsNullable=true)]
    public partial class ForeignCitizenBasicData : InformationObject<ForeignCitizenBasicData> {
        
        private ForeignCitizenNames namesField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private ForeignCitizenPlaceOfBirth placeOfBirthField;
        
        private ForeignCitizenIdentityDocument identityDocumentField;
        
        /// <summary>
        /// ForeignCitizenBasicData class constructor
        /// </summary>
        public ForeignCitizenBasicData() {
            this.identityDocumentField = new ForeignCitizenIdentityDocument();
            this.placeOfBirthField = new ForeignCitizenPlaceOfBirth();
            this.namesField = new ForeignCitizenNames();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ForeignCitizenNames Names {
            get {
                return this.namesField;
            }
            set {
                if ((this.namesField != null)) {
                    if ((namesField.Equals(value) != true)) {
                        this.namesField = value;
                        this.OnPropertyChanged("Names");
                    }
                }
                else {
                    this.namesField = value;
                    this.OnPropertyChanged("Names");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                if ((birthDateField.Equals(value) != true)) {
                    this.birthDateField = value;
                    this.OnPropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                if ((birthDateFieldSpecified.Equals(value) != true)) {
                    this.birthDateFieldSpecified = value;
                    this.OnPropertyChanged("BirthDateSpecified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ForeignCitizenPlaceOfBirth PlaceOfBirth {
            get {
                return this.placeOfBirthField;
            }
            set {
                if ((this.placeOfBirthField != null)) {
                    if ((placeOfBirthField.Equals(value) != true)) {
                        this.placeOfBirthField = value;
                        this.OnPropertyChanged("PlaceOfBirth");
                    }
                }
                else {
                    this.placeOfBirthField = value;
                    this.OnPropertyChanged("PlaceOfBirth");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ForeignCitizenIdentityDocument IdentityDocument {
            get {
                return this.identityDocumentField;
            }
            set {
                if ((this.identityDocumentField != null)) {
                    if ((identityDocumentField.Equals(value) != true)) {
                        this.identityDocumentField = value;
                        this.OnPropertyChanged("IdentityDocument");
                    }
                }
                else {
                    this.identityDocumentField = value;
                    this.OnPropertyChanged("IdentityDocument");
                }
            }
        }
    }
}
