// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings>TechnoLogica.Eservices.InformationObjects.Nomenclatures</CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using TechnoLogica.Eservices.InformationObjects.Nomenclatures;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ereg.egov.bg/segment/0009-000152")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ereg.egov.bg/segment/0009-000152", IsNullable = true)]
    public partial class ElectronicAdministrativeServiceHeader : InformationObject<ElectronicAdministrativeServiceHeader>
    {

        private string sUNAUServiceURIField;

        private DocumentTypeURI documentTypeURIField;

        private string documentTypeNameField;

        private ElectronicServiceProviderBasicData electronicServiceProviderBasicDataField;

        private ElectronicServiceApplicant electronicServiceApplicantField;

        private ElectronicServiceApplicantContactData electronicServiceApplicantContactDataField;

        private ApplicationType applicationTypeField;

        private bool applicationTypeFieldSpecified;

        private string sUNAUServiceNameField;

        private DocumentURI documentURIField;

        private bool sendApplicationWithReceiptAcknowledgedMessageField;

        private bool sendApplicationWithReceiptAcknowledgedMessageFieldSpecified;

        /// <summary>
        /// ElectronicAdministrativeServiceHeader class constructor
        /// </summary>
        public ElectronicAdministrativeServiceHeader()
        {
            this.documentURIField = new DocumentURI();
            this.electronicServiceApplicantContactDataField = new ElectronicServiceApplicantContactData();
            this.electronicServiceApplicantField = new ElectronicServiceApplicant();
            this.electronicServiceProviderBasicDataField = new ElectronicServiceProviderBasicData();
            this.documentTypeURIField = new DocumentTypeURI();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string SUNAUServiceURI
        {
            get
            {
                return this.sUNAUServiceURIField;
            }
            set
            {
                if ((this.sUNAUServiceURIField != null))
                {
                    if ((sUNAUServiceURIField.Equals(value) != true))
                    {
                        this.sUNAUServiceURIField = value;
                        this.OnPropertyChanged("SUNAUServiceURI");
                    }
                }
                else
                {
                    this.sUNAUServiceURIField = value;
                    this.OnPropertyChanged("SUNAUServiceURI");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public DocumentTypeURI DocumentTypeURI
        {
            get
            {
                return this.documentTypeURIField;
            }
            set
            {
                if ((this.documentTypeURIField != null))
                {
                    if ((documentTypeURIField.Equals(value) != true))
                    {
                        this.documentTypeURIField = value;
                        this.OnPropertyChanged("DocumentTypeURI");
                    }
                }
                else
                {
                    this.documentTypeURIField = value;
                    this.OnPropertyChanged("DocumentTypeURI");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string DocumentTypeName
        {
            get
            {
                return this.documentTypeNameField;
            }
            set
            {
                if ((this.documentTypeNameField != null))
                {
                    if ((documentTypeNameField.Equals(value) != true))
                    {
                        this.documentTypeNameField = value;
                        this.OnPropertyChanged("DocumentTypeName");
                    }
                }
                else
                {
                    this.documentTypeNameField = value;
                    this.OnPropertyChanged("DocumentTypeName");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public ElectronicServiceProviderBasicData ElectronicServiceProviderBasicData
        {
            get
            {
                return this.electronicServiceProviderBasicDataField;
            }
            set
            {
                if ((this.electronicServiceProviderBasicDataField != null))
                {
                    if ((electronicServiceProviderBasicDataField.Equals(value) != true))
                    {
                        this.electronicServiceProviderBasicDataField = value;
                        this.OnPropertyChanged("ElectronicServiceProviderBasicData");
                    }
                }
                else
                {
                    this.electronicServiceProviderBasicDataField = value;
                    this.OnPropertyChanged("ElectronicServiceProviderBasicData");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public ElectronicServiceApplicant ElectronicServiceApplicant
        {
            get
            {
                return this.electronicServiceApplicantField;
            }
            set
            {
                if ((this.electronicServiceApplicantField != null))
                {
                    if ((electronicServiceApplicantField.Equals(value) != true))
                    {
                        this.electronicServiceApplicantField = value;
                        this.OnPropertyChanged("ElectronicServiceApplicant");
                    }
                }
                else
                {
                    this.electronicServiceApplicantField = value;
                    this.OnPropertyChanged("ElectronicServiceApplicant");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public ElectronicServiceApplicantContactData ElectronicServiceApplicantContactData
        {
            get
            {
                return this.electronicServiceApplicantContactDataField;
            }
            set
            {
                if ((this.electronicServiceApplicantContactDataField != null))
                {
                    if ((electronicServiceApplicantContactDataField.Equals(value) != true))
                    {
                        this.electronicServiceApplicantContactDataField = value;
                        this.OnPropertyChanged("ElectronicServiceApplicantContactData");
                    }
                }
                else
                {
                    this.electronicServiceApplicantContactDataField = value;
                    this.OnPropertyChanged("ElectronicServiceApplicantContactData");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public ApplicationType ApplicationType
        {
            get
            {
                return this.applicationTypeField;
            }
            set
            {
                if ((applicationTypeField.Equals(value) != true))
                {
                    this.applicationTypeField = value;
                    this.OnPropertyChanged("ApplicationType");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplicationTypeSpecified
        {
            get
            {
                return this.applicationTypeFieldSpecified;
            }
            set
            {
                if ((applicationTypeFieldSpecified.Equals(value) != true))
                {
                    this.applicationTypeFieldSpecified = value;
                    this.OnPropertyChanged("ApplicationTypeSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string SUNAUServiceName
        {
            get
            {
                return this.sUNAUServiceNameField;
            }
            set
            {
                if ((this.sUNAUServiceNameField != null))
                {
                    if ((sUNAUServiceNameField.Equals(value) != true))
                    {
                        this.sUNAUServiceNameField = value;
                        this.OnPropertyChanged("SUNAUServiceName");
                    }
                }
                else
                {
                    this.sUNAUServiceNameField = value;
                    this.OnPropertyChanged("SUNAUServiceName");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public DocumentURI DocumentURI
        {
            get
            {
                return this.documentURIField;
            }
            set
            {
                if ((this.documentURIField != null))
                {
                    if ((documentURIField.Equals(value) != true))
                    {
                        this.documentURIField = value;
                        this.OnPropertyChanged("DocumentURI");
                    }
                }
                else
                {
                    this.documentURIField = value;
                    this.OnPropertyChanged("DocumentURI");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public bool SendApplicationWithReceiptAcknowledgedMessage
        {
            get
            {
                return this.sendApplicationWithReceiptAcknowledgedMessageField;
            }
            set
            {
                if ((sendApplicationWithReceiptAcknowledgedMessageField.Equals(value) != true))
                {
                    this.sendApplicationWithReceiptAcknowledgedMessageField = value;
                    this.OnPropertyChanged("SendApplicationWithReceiptAcknowledgedMessage");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendApplicationWithReceiptAcknowledgedMessageSpecified
        {
            get
            {
                return this.sendApplicationWithReceiptAcknowledgedMessageFieldSpecified;
            }
            set
            {
                if ((sendApplicationWithReceiptAcknowledgedMessageFieldSpecified.Equals(value) != true))
                {
                    this.sendApplicationWithReceiptAcknowledgedMessageFieldSpecified = value;
                    this.OnPropertyChanged("SendApplicationWithReceiptAcknowledgedMessageSpecified");
                }
            }
        }
    }
}
