// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ereg.egov.bg/segment/0009-000201")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ereg.egov.bg/segment/0009-000201", IsNullable=true)]
    public partial class RealEstateNeighboringProperty : InformationObject<RealEstateNeighboringProperty> {
        
        private string neighboringPropertyDirectionField;
        
        private RealEstateCadastreIdentifier realEstateCadastreIdentifierField;
        
        private string neighboringPropertyDescriptionField;
        
        /// <summary>
        /// RealEstateNeighboringProperty class constructor
        /// </summary>
        public RealEstateNeighboringProperty() {
            this.realEstateCadastreIdentifierField = new RealEstateCadastreIdentifier();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NeighboringPropertyDirection {
            get {
                return this.neighboringPropertyDirectionField;
            }
            set {
                if ((this.neighboringPropertyDirectionField != null)) {
                    if ((neighboringPropertyDirectionField.Equals(value) != true)) {
                        this.neighboringPropertyDirectionField = value;
                        this.OnPropertyChanged("NeighboringPropertyDirection");
                    }
                }
                else {
                    this.neighboringPropertyDirectionField = value;
                    this.OnPropertyChanged("NeighboringPropertyDirection");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RealEstateCadastreIdentifier RealEstateCadastreIdentifier {
            get {
                return this.realEstateCadastreIdentifierField;
            }
            set {
                if ((this.realEstateCadastreIdentifierField != null)) {
                    if ((realEstateCadastreIdentifierField.Equals(value) != true)) {
                        this.realEstateCadastreIdentifierField = value;
                        this.OnPropertyChanged("RealEstateCadastreIdentifier");
                    }
                }
                else {
                    this.realEstateCadastreIdentifierField = value;
                    this.OnPropertyChanged("RealEstateCadastreIdentifier");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NeighboringPropertyDescription {
            get {
                return this.neighboringPropertyDescriptionField;
            }
            set {
                if ((this.neighboringPropertyDescriptionField != null)) {
                    if ((neighboringPropertyDescriptionField.Equals(value) != true)) {
                        this.neighboringPropertyDescriptionField = value;
                        this.OnPropertyChanged("NeighboringPropertyDescription");
                    }
                }
                else {
                    this.neighboringPropertyDescriptionField = value;
                    this.OnPropertyChanged("NeighboringPropertyDescription");
                }
            }
        }
    }
}
