// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.31926
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ereg.egov.bg/segment/0009-000024")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ereg.egov.bg/segment/0009-000024", IsNullable = true)]
    public partial class RegisteredErrorInDocumentContent : InformationObject<RegisteredErrorInDocumentContent>
    {

        private TermURI termURIField;

        private string errorDescriptionField;

        private string documentElementReferenceField;

        /// <summary>
        /// RegisteredErrorInDocumentContent class constructor
        /// </summary>
        public RegisteredErrorInDocumentContent()
        {
            this.termURIField = new TermURI();
        }

        public TermURI TermURI
        {
            get
            {
                return this.termURIField;
            }
            set
            {
                if ((this.termURIField != null))
                {
                    if ((termURIField.Equals(value) != true))
                    {
                        this.termURIField = value;
                        this.OnPropertyChanged("TermURI");
                    }
                }
                else
                {
                    this.termURIField = value;
                    this.OnPropertyChanged("TermURI");
                }
            }
        }

        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                if ((this.errorDescriptionField != null))
                {
                    if ((errorDescriptionField.Equals(value) != true))
                    {
                        this.errorDescriptionField = value;
                        this.OnPropertyChanged("ErrorDescription");
                    }
                }
                else
                {
                    this.errorDescriptionField = value;
                    this.OnPropertyChanged("ErrorDescription");
                }
            }
        }

        public string DocumentElementReference
        {
            get
            {
                return this.documentElementReferenceField;
            }
            set
            {
                if ((this.documentElementReferenceField != null))
                {
                    if ((documentElementReferenceField.Equals(value) != true))
                    {
                        this.documentElementReferenceField = value;
                        this.OnPropertyChanged("DocumentElementReference");
                    }
                }
                else
                {
                    this.documentElementReferenceField = value;
                    this.OnPropertyChanged("DocumentElementReference");
                }
            }
        }
    }
}
