// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ereg.egov.bg/segment/0009-000195")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ereg.egov.bg/segment/0009-000195", IsNullable = true)]
    public partial class RealEstateAddressData : InformationObject<RealEstateAddressData>
    {

        private string districtCodeField;

        private string districtNameField;

        private string municipalityCodeField;

        private string municipalityNameField;

        private string territorialUnitEKATTECodeField;

        private string territorialUnitEKATTENameField;

        private RealEstateAddressDataLandOrUrbanPropertyAddress landOrUrbanPropertyAddressField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string DistrictCode
        {
            get
            {
                return this.districtCodeField;
            }
            set
            {
                if ((this.districtCodeField != null))
                {
                    if ((districtCodeField.Equals(value) != true))
                    {
                        this.districtCodeField = value;
                        this.OnPropertyChanged("DistrictCode");
                    }
                }
                else
                {
                    this.districtCodeField = value;
                    this.OnPropertyChanged("DistrictCode");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string DistrictName
        {
            get
            {
                return this.districtNameField;
            }
            set
            {
                if ((this.districtNameField != null))
                {
                    if ((districtNameField.Equals(value) != true))
                    {
                        this.districtNameField = value;
                        this.OnPropertyChanged("DistrictName");
                    }
                }
                else
                {
                    this.districtNameField = value;
                    this.OnPropertyChanged("DistrictName");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string MunicipalityCode
        {
            get
            {
                return this.municipalityCodeField;
            }
            set
            {
                if ((this.municipalityCodeField != null))
                {
                    if ((municipalityCodeField.Equals(value) != true))
                    {
                        this.municipalityCodeField = value;
                        this.OnPropertyChanged("MunicipalityCode");
                    }
                }
                else
                {
                    this.municipalityCodeField = value;
                    this.OnPropertyChanged("MunicipalityCode");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string MunicipalityName
        {
            get
            {
                return this.municipalityNameField;
            }
            set
            {
                if ((this.municipalityNameField != null))
                {
                    if ((municipalityNameField.Equals(value) != true))
                    {
                        this.municipalityNameField = value;
                        this.OnPropertyChanged("MunicipalityName");
                    }
                }
                else
                {
                    this.municipalityNameField = value;
                    this.OnPropertyChanged("MunicipalityName");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string TerritorialUnitEKATTECode
        {
            get
            {
                return this.territorialUnitEKATTECodeField;
            }
            set
            {
                if ((this.territorialUnitEKATTECodeField != null))
                {
                    if ((territorialUnitEKATTECodeField.Equals(value) != true))
                    {
                        this.territorialUnitEKATTECodeField = value;
                        this.OnPropertyChanged("TerritorialUnitEKATTECode");
                    }
                }
                else
                {
                    this.territorialUnitEKATTECodeField = value;
                    this.OnPropertyChanged("TerritorialUnitEKATTECode");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string TerritorialUnitEKATTEName
        {
            get
            {
                return this.territorialUnitEKATTENameField;
            }
            set
            {
                if ((this.territorialUnitEKATTENameField != null))
                {
                    if ((territorialUnitEKATTENameField.Equals(value) != true))
                    {
                        this.territorialUnitEKATTENameField = value;
                        this.OnPropertyChanged("TerritorialUnitEKATTEName");
                    }
                }
                else
                {
                    this.territorialUnitEKATTENameField = value;
                    this.OnPropertyChanged("TerritorialUnitEKATTEName");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public RealEstateAddressDataLandOrUrbanPropertyAddress LandOrUrbanPropertyAddress
        {
            get
            {
                return this.landOrUrbanPropertyAddressField;
            }
            set
            {
                if ((this.landOrUrbanPropertyAddressField != null))
                {
                    if ((landOrUrbanPropertyAddressField.Equals(value) != true))
                    {
                        this.landOrUrbanPropertyAddressField = value;
                        this.OnPropertyChanged("LandOrUrbanPropertyAddress");
                    }
                }
                else
                {
                    this.landOrUrbanPropertyAddressField = value;
                    this.OnPropertyChanged("LandOrUrbanPropertyAddress");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ereg.egov.bg/segment/0009-000195")]
    public partial class RealEstateAddressDataLandOrUrbanPropertyAddress : InformationObject<RealEstateAddressDataLandOrUrbanPropertyAddress>
    {

        private string[] itemsField;

        private ItemsChoiceTypeAddressData[] itemsElementNameField;

        [System.Xml.Serialization.XmlElementAttribute("BuildingNumber", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Entrance", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Floor", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("LandPropertyArealName", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("ResidentialComplex", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("SeparateBuildingUnitFunctionalDesignationCode", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("SeparateBuildingUnitFunctionalDesignationName", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("SeparateBuildingUnitNumber", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("StreetBoulevardSquare", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("StreetBoulevardSquareNumber", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                if ((this.itemsField != null))
                {
                    if ((itemsField.Equals(value) != true))
                    {
                        this.itemsField = value;
                        this.OnPropertyChanged("Items");
                    }
                }
                else
                {
                    this.itemsField = value;
                    this.OnPropertyChanged("Items");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceTypeAddressData[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                if ((this.itemsElementNameField != null))
                {
                    if ((itemsElementNameField.Equals(value) != true))
                    {
                        this.itemsElementNameField = value;
                        this.OnPropertyChanged("ItemsElementName");
                    }
                }
                else
                {
                    this.itemsElementNameField = value;
                    this.OnPropertyChanged("ItemsElementName");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ereg.egov.bg/segment/0009-000195", IncludeInSchema = false)]
    public enum ItemsChoiceTypeAddressData
    {

        /// <remarks/>
        BuildingNumber = 4,

        /// <remarks/>
        Entrance = 5,

        /// <remarks/>
        Floor = 6,

        /// <remarks/>
        LandPropertyArealName = 10,

        /// <remarks/>
        ResidentialComplex = 3,

        /// <remarks/>
        SeparateBuildingUnitFunctionalDesignationCode = 7,

        /// <remarks/>
        SeparateBuildingUnitFunctionalDesignationName = 8,

        /// <remarks/>
        SeparateBuildingUnitNumber = 9,

        /// <remarks/>
        StreetBoulevardSquare = 1,

        /// <remarks/>
        StreetBoulevardSquareNumber =2
    }
}
