// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings>TechnoLogica.Eservices.InformationObjects.Nomenclatures</CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using TechnoLogica.Eservices.InformationObjects.Nomenclatures;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ereg.egov.bg/segment/0009-000202")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ereg.egov.bg/segment/0009-000202", IsNullable = true)]
    public partial class StateAndMunicipalPropertyIdentifyingData : InformationObject<StateAndMunicipalPropertyIdentifyingData>
    {

        private RealEstateType realEstateTypeField;

        private bool realEstateTypeFieldSpecified;

        private RealEstateAddressData realEstateAddressField;

        private RealEstateCadastreIdentifier realEstateCadastreIdentifierField;

        private StateAndMunicipalPropertyIdentifyingDataLandPropertyOldIdentifier landPropertyOldIdentifierField;

        private StateAndMunicipalPropertyIdentifyingDataActIdentifier actIdentifierField;

        private List<RealEstateNeighboringProperty> realEstateNeighboringPropertiesField;

        private string realEstateBatchNumberField;

        private string accordingToDocumentsQuadratureField;

        private string realQuadratureField;

        private string realEstateAdditionalInformationField;

        /// <summary>
        /// StateAndMunicipalPropertyIdentifyingData class constructor
        /// </summary>
        public StateAndMunicipalPropertyIdentifyingData()
        {
            this.realEstateNeighboringPropertiesField = new List<RealEstateNeighboringProperty>();
            this.actIdentifierField = new StateAndMunicipalPropertyIdentifyingDataActIdentifier();
            this.landPropertyOldIdentifierField = new StateAndMunicipalPropertyIdentifyingDataLandPropertyOldIdentifier();
            this.realEstateCadastreIdentifierField = new RealEstateCadastreIdentifier();
            this.realEstateAddressField = new RealEstateAddressData();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public RealEstateType RealEstateType
        {
            get
            {
                return this.realEstateTypeField;
            }
            set
            {
                if ((realEstateTypeField.Equals(value) != true))
                {
                    this.realEstateTypeField = value;
                    this.OnPropertyChanged("RealEstateType");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RealEstateTypeSpecified
        {
            get
            {
                return this.realEstateTypeFieldSpecified;
            }
            set
            {
                if ((realEstateTypeFieldSpecified.Equals(value) != true))
                {
                    this.realEstateTypeFieldSpecified = value;
                    this.OnPropertyChanged("RealEstateTypeSpecified");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public RealEstateAddressData RealEstateAddress
        {
            get
            {
                return this.realEstateAddressField;
            }
            set
            {
                if ((this.realEstateAddressField != null))
                {
                    if ((realEstateAddressField.Equals(value) != true))
                    {
                        this.realEstateAddressField = value;
                        this.OnPropertyChanged("RealEstateAddress");
                    }
                }
                else
                {
                    this.realEstateAddressField = value;
                    this.OnPropertyChanged("RealEstateAddress");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public RealEstateCadastreIdentifier RealEstateCadastreIdentifier
        {
            get
            {
                return this.realEstateCadastreIdentifierField;
            }
            set
            {
                if ((this.realEstateCadastreIdentifierField != null))
                {
                    if ((realEstateCadastreIdentifierField.Equals(value) != true))
                    {
                        this.realEstateCadastreIdentifierField = value;
                        this.OnPropertyChanged("RealEstateCadastreIdentifier");
                    }
                }
                else
                {
                    this.realEstateCadastreIdentifierField = value;
                    this.OnPropertyChanged("RealEstateCadastreIdentifier");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public StateAndMunicipalPropertyIdentifyingDataLandPropertyOldIdentifier LandPropertyOldIdentifier
        {
            get
            {
                return this.landPropertyOldIdentifierField;
            }
            set
            {
                if ((this.landPropertyOldIdentifierField != null))
                {
                    if ((landPropertyOldIdentifierField.Equals(value) != true))
                    {
                        this.landPropertyOldIdentifierField = value;
                        this.OnPropertyChanged("LandPropertyOldIdentifier");
                    }
                }
                else
                {
                    this.landPropertyOldIdentifierField = value;
                    this.OnPropertyChanged("LandPropertyOldIdentifier");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public StateAndMunicipalPropertyIdentifyingDataActIdentifier ActIdentifier
        {
            get
            {
                return this.actIdentifierField;
            }
            set
            {
                if ((this.actIdentifierField != null))
                {
                    if ((actIdentifierField.Equals(value) != true))
                    {
                        this.actIdentifierField = value;
                        this.OnPropertyChanged("ActIdentifier");
                    }
                }
                else
                {
                    this.actIdentifierField = value;
                    this.OnPropertyChanged("ActIdentifier");
                }
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public List<RealEstateNeighboringProperty> RealEstateNeighboringProperties
        {
            get
            {
                return this.realEstateNeighboringPropertiesField;
            }
            set
            {
                if ((this.realEstateNeighboringPropertiesField != null))
                {
                    if ((realEstateNeighboringPropertiesField.Equals(value) != true))
                    {
                        this.realEstateNeighboringPropertiesField = value;
                        this.OnPropertyChanged("RealEstateNeighboringProperties");
                    }
                }
                else
                {
                    this.realEstateNeighboringPropertiesField = value;
                    this.OnPropertyChanged("RealEstateNeighboringProperties");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string RealEstateBatchNumber
        {
            get
            {
                return this.realEstateBatchNumberField;
            }
            set
            {
                if ((this.realEstateBatchNumberField != null))
                {
                    if ((realEstateBatchNumberField.Equals(value) != true))
                    {
                        this.realEstateBatchNumberField = value;
                        this.OnPropertyChanged("RealEstateBatchNumber");
                    }
                }
                else
                {
                    this.realEstateBatchNumberField = value;
                    this.OnPropertyChanged("RealEstateBatchNumber");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string AccordingToDocumentsQuadrature
        {
            get
            {
                return this.accordingToDocumentsQuadratureField;
            }
            set
            {
                if ((this.accordingToDocumentsQuadratureField != null))
                {
                    if ((accordingToDocumentsQuadratureField.Equals(value) != true))
                    {
                        this.accordingToDocumentsQuadratureField = value;
                        this.OnPropertyChanged("AccordingToDocumentsQuadrature");
                    }
                }
                else
                {
                    this.accordingToDocumentsQuadratureField = value;
                    this.OnPropertyChanged("AccordingToDocumentsQuadrature");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string RealQuadrature
        {
            get
            {
                return this.realQuadratureField;
            }
            set
            {
                if ((this.realQuadratureField != null))
                {
                    if ((realQuadratureField.Equals(value) != true))
                    {
                        this.realQuadratureField = value;
                        this.OnPropertyChanged("RealQuadrature");
                    }
                }
                else
                {
                    this.realQuadratureField = value;
                    this.OnPropertyChanged("RealQuadrature");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string RealEstateAdditionalInformation
        {
            get
            {
                return this.realEstateAdditionalInformationField;
            }
            set
            {
                if ((this.realEstateAdditionalInformationField != null))
                {
                    if ((realEstateAdditionalInformationField.Equals(value) != true))
                    {
                        this.realEstateAdditionalInformationField = value;
                        this.OnPropertyChanged("RealEstateAdditionalInformation");
                    }
                }
                else
                {
                    this.realEstateAdditionalInformationField = value;
                    this.OnPropertyChanged("RealEstateAdditionalInformation");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ereg.egov.bg/segment/0009-000202")]
    public partial class StateAndMunicipalPropertyIdentifyingDataLandPropertyOldIdentifier : InformationObject<StateAndMunicipalPropertyIdentifyingDataLandPropertyOldIdentifier>
    {

        private object itemField;

        [System.Xml.Serialization.XmlElementAttribute("FarmlandAndForestLandPropertyOldIdentifier", typeof(FarmlandAndForestLandPropertyOldIdentifier), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("UrbanLandPropertyOldIdentifier", typeof(UrbanLandPropertyOldIdentifier), Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                if ((this.itemField != null))
                {
                    if ((itemField.Equals(value) != true))
                    {
                        this.itemField = value;
                        this.OnPropertyChanged("Item");
                    }
                }
                else
                {
                    this.itemField = value;
                    this.OnPropertyChanged("Item");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ereg.egov.bg/segment/0009-000202")]
    public partial class StateAndMunicipalPropertyIdentifyingDataActIdentifier : InformationObject<StateAndMunicipalPropertyIdentifyingDataActIdentifier>
    {

        private object itemField;

        [System.Xml.Serialization.XmlElementAttribute("MunicipalPropertyActIdentifier", typeof(MunicipalPropertyActIdentifier), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("StatePropertyActIdentifier", typeof(StatePropertyActIdentifier), Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                if ((this.itemField != null))
                {
                    if ((itemField.Equals(value) != true))
                    {
                        this.itemField = value;
                        this.OnPropertyChanged("Item");
                    }
                }
                else
                {
                    this.itemField = value;
                    this.OnPropertyChanged("Item");
                }
            }
        }
    }
}
