// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>True</OrderXMLAttrib><EnableEncoding>True</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings>TechnoLogica.Eservices.InformationObjects.Nomenclatures</CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using TechnoLogica.Eservices.InformationObjects.Nomenclatures;
    using System.IO;
    using System.Text;
    using System.Xml;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ereg.egov.bg/segment/R-0009-000001")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://ereg.egov.bg/segment/R-0009-000001", IsNullable = false)]
    public partial class AISKAOIntegrationEserviceStartApplication : InformationObject<AISKAOIntegrationEserviceStartApplication>
    {

        private ElectronicAdministrativeServiceHeader electronicAdministrativeServiceHeaderField;

        private bool serviceTermTypeFieldSpecified;

        private ServiceApplicantReceiptData serviceApplicantReceiptDataField;

        private string additionalInformationField;

        private string resultDocumentTypeURIField;

        private List<object> attachedDocumentsField;

        private ElectronicAdministrativeServiceFooter electronicAdministrativeServiceFooterField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ServiceTermType ServiceTermType { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceTermTypeSpecified { get; set; }

        /// <summary>
        /// Допълнителна информация
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string AdditionalInformation { get; set; }

        /// <summary>
        /// УРИ на тип на документ на резултата в АИСКАО
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string ResultDocumentTypeURI { get; set; }


        /// <summary>
        /// Данни за заявителя и за получателя (титуляра ) на заявяваната електронна услуга
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ElectronicAdministrativeServiceHeader ElectronicAdministrativeServiceHeader
        {
            get
            {
                if ((this.electronicAdministrativeServiceHeaderField == null))
                {
                    this.electronicAdministrativeServiceHeaderField = new ElectronicAdministrativeServiceHeader();
                }
                return this.electronicAdministrativeServiceHeaderField;
            }
            set
            {
                this.electronicAdministrativeServiceHeaderField = value;
            }
        }

        /// <summary>
        /// Начин на получаване и пощенски адрес или друга администрация, където да бъде получен резултата
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public ServiceApplicantReceiptData ServiceApplicantReceiptData
        {
            get
            {
                if ((this.serviceApplicantReceiptDataField == null))
                {
                    this.serviceApplicantReceiptDataField = new ServiceApplicantReceiptData();
                }
                return this.serviceApplicantReceiptDataField;
            }
            set
            {
                this.serviceApplicantReceiptDataField = value;
            }
        }

        /// <summary>
        /// Прикачени документи, XML или бинарни файлове
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(typeof(AttachedDocument), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AttachedXmlDocument", typeof(ElectronicDocumentXml), IsNullable = false)]
        public List<object> AttachedDocuments
        {
            get
            {
                if ((this.attachedDocumentsField == null))
                {
                    this.attachedDocumentsField = new List<object>();
                }
                return this.attachedDocumentsField;
            }
            set
            {
                this.attachedDocumentsField = value;
            }
        }

        /// <summary>
        /// Електронен подпис и време на подписване
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public ElectronicAdministrativeServiceFooter ElectronicAdministrativeServiceFooter
        {
            get
            {
                if ((this.electronicAdministrativeServiceFooterField == null))
                {
                    this.electronicAdministrativeServiceFooterField = new ElectronicAdministrativeServiceFooter();
                }
                return this.electronicAdministrativeServiceFooterField;
            }
            set
            {
                this.electronicAdministrativeServiceFooterField = value;
            }
        }
    }
}
