// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ereg.egov.bg/segment/R-1085")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ereg.egov.bg/segment/R-1085", IsNullable=true)]
    public partial class CROZRegistrationEntryBasicData : InformationObject<CROZRegistrationEntryBasicData> {
        
        private string cROZRegistrationNumberField;
        
        private bool cROZRegisterEntryIsInConditionalStatusField;
        
        private bool cROZRegisterEntryIsInConditionalStatusFieldSpecified;
        
        private bool cROZRegisterEntryIsArchivedField;
        
        private bool cROZRegisterEntryIsArchivedFieldSpecified;
        
        private string cROZRegistrationEntryTypeCodeField;
        
        private string cROZRegistrationEntryTypeNameField;
        
        private System.DateTime cROZConsignmentRegistrationDateTimeField;
        
        private bool cROZConsignmentRegistrationDateTimeFieldSpecified;
        
        private System.DateTime cROZRegistrationEntryTerminationDateField;
        
        private bool cROZRegistrationEntryTerminationDateFieldSpecified;
        
        private int cROZRegistrationEntryOpticleArchivePagesCountField;
        
        private bool cROZRegistrationEntryOpticleArchivePagesCountFieldSpecified;
        
        private bool cROZRegisterEntryProcedureIsCompletedField;
        
        private bool cROZRegisterEntryProcedureIsCompletedFieldSpecified;
        
        private List<CROZOpticalArchiveFieldSeventeenImageData> cROZOpticalArchiveFieldSeventeenImageDatasField;
        
        private string cROZPledgeOnClaimsRegistrationEntryNumberField;
        
        private CROZDistrainSecuredClaimsRegistrationEntryNumbersData cROZDistrainSecuredClaimsRegistrationEntryNumbersDataField;
        
        /// <summary>
        /// CROZRegistrationEntryBasicData class constructor
        /// </summary>
        public CROZRegistrationEntryBasicData() {
            this.cROZDistrainSecuredClaimsRegistrationEntryNumbersDataField = new CROZDistrainSecuredClaimsRegistrationEntryNumbersData();
            this.cROZOpticalArchiveFieldSeventeenImageDatasField = new List<CROZOpticalArchiveFieldSeventeenImageData>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CROZRegistrationNumber {
            get {
                return this.cROZRegistrationNumberField;
            }
            set {
                if ((this.cROZRegistrationNumberField != null)) {
                    if ((cROZRegistrationNumberField.Equals(value) != true)) {
                        this.cROZRegistrationNumberField = value;
                        this.OnPropertyChanged("CROZRegistrationNumber");
                    }
                }
                else {
                    this.cROZRegistrationNumberField = value;
                    this.OnPropertyChanged("CROZRegistrationNumber");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool CROZRegisterEntryIsInConditionalStatus {
            get {
                return this.cROZRegisterEntryIsInConditionalStatusField;
            }
            set {
                if ((cROZRegisterEntryIsInConditionalStatusField.Equals(value) != true)) {
                    this.cROZRegisterEntryIsInConditionalStatusField = value;
                    this.OnPropertyChanged("CROZRegisterEntryIsInConditionalStatus");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CROZRegisterEntryIsInConditionalStatusSpecified {
            get {
                return this.cROZRegisterEntryIsInConditionalStatusFieldSpecified;
            }
            set {
                if ((cROZRegisterEntryIsInConditionalStatusFieldSpecified.Equals(value) != true)) {
                    this.cROZRegisterEntryIsInConditionalStatusFieldSpecified = value;
                    this.OnPropertyChanged("CROZRegisterEntryIsInConditionalStatusSpecified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool CROZRegisterEntryIsArchived {
            get {
                return this.cROZRegisterEntryIsArchivedField;
            }
            set {
                if ((cROZRegisterEntryIsArchivedField.Equals(value) != true)) {
                    this.cROZRegisterEntryIsArchivedField = value;
                    this.OnPropertyChanged("CROZRegisterEntryIsArchived");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CROZRegisterEntryIsArchivedSpecified {
            get {
                return this.cROZRegisterEntryIsArchivedFieldSpecified;
            }
            set {
                if ((cROZRegisterEntryIsArchivedFieldSpecified.Equals(value) != true)) {
                    this.cROZRegisterEntryIsArchivedFieldSpecified = value;
                    this.OnPropertyChanged("CROZRegisterEntryIsArchivedSpecified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CROZRegistrationEntryTypeCode {
            get {
                return this.cROZRegistrationEntryTypeCodeField;
            }
            set {
                if ((this.cROZRegistrationEntryTypeCodeField != null)) {
                    if ((cROZRegistrationEntryTypeCodeField.Equals(value) != true)) {
                        this.cROZRegistrationEntryTypeCodeField = value;
                        this.OnPropertyChanged("CROZRegistrationEntryTypeCode");
                    }
                }
                else {
                    this.cROZRegistrationEntryTypeCodeField = value;
                    this.OnPropertyChanged("CROZRegistrationEntryTypeCode");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CROZRegistrationEntryTypeName {
            get {
                return this.cROZRegistrationEntryTypeNameField;
            }
            set {
                if ((this.cROZRegistrationEntryTypeNameField != null)) {
                    if ((cROZRegistrationEntryTypeNameField.Equals(value) != true)) {
                        this.cROZRegistrationEntryTypeNameField = value;
                        this.OnPropertyChanged("CROZRegistrationEntryTypeName");
                    }
                }
                else {
                    this.cROZRegistrationEntryTypeNameField = value;
                    this.OnPropertyChanged("CROZRegistrationEntryTypeName");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime CROZConsignmentRegistrationDateTime {
            get {
                return this.cROZConsignmentRegistrationDateTimeField;
            }
            set {
                if ((cROZConsignmentRegistrationDateTimeField.Equals(value) != true)) {
                    this.cROZConsignmentRegistrationDateTimeField = value;
                    this.OnPropertyChanged("CROZConsignmentRegistrationDateTime");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CROZConsignmentRegistrationDateTimeSpecified {
            get {
                return this.cROZConsignmentRegistrationDateTimeFieldSpecified;
            }
            set {
                if ((cROZConsignmentRegistrationDateTimeFieldSpecified.Equals(value) != true)) {
                    this.cROZConsignmentRegistrationDateTimeFieldSpecified = value;
                    this.OnPropertyChanged("CROZConsignmentRegistrationDateTimeSpecified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime CROZRegistrationEntryTerminationDate {
            get {
                return this.cROZRegistrationEntryTerminationDateField;
            }
            set {
                if ((cROZRegistrationEntryTerminationDateField.Equals(value) != true)) {
                    this.cROZRegistrationEntryTerminationDateField = value;
                    this.OnPropertyChanged("CROZRegistrationEntryTerminationDate");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CROZRegistrationEntryTerminationDateSpecified {
            get {
                return this.cROZRegistrationEntryTerminationDateFieldSpecified;
            }
            set {
                if ((cROZRegistrationEntryTerminationDateFieldSpecified.Equals(value) != true)) {
                    this.cROZRegistrationEntryTerminationDateFieldSpecified = value;
                    this.OnPropertyChanged("CROZRegistrationEntryTerminationDateSpecified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CROZRegistrationEntryOpticleArchivePagesCount {
            get {
                return this.cROZRegistrationEntryOpticleArchivePagesCountField;
            }
            set {
                if ((cROZRegistrationEntryOpticleArchivePagesCountField.Equals(value) != true)) {
                    this.cROZRegistrationEntryOpticleArchivePagesCountField = value;
                    this.OnPropertyChanged("CROZRegistrationEntryOpticleArchivePagesCount");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CROZRegistrationEntryOpticleArchivePagesCountSpecified {
            get {
                return this.cROZRegistrationEntryOpticleArchivePagesCountFieldSpecified;
            }
            set {
                if ((cROZRegistrationEntryOpticleArchivePagesCountFieldSpecified.Equals(value) != true)) {
                    this.cROZRegistrationEntryOpticleArchivePagesCountFieldSpecified = value;
                    this.OnPropertyChanged("CROZRegistrationEntryOpticleArchivePagesCountSpecified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool CROZRegisterEntryProcedureIsCompleted {
            get {
                return this.cROZRegisterEntryProcedureIsCompletedField;
            }
            set {
                if ((cROZRegisterEntryProcedureIsCompletedField.Equals(value) != true)) {
                    this.cROZRegisterEntryProcedureIsCompletedField = value;
                    this.OnPropertyChanged("CROZRegisterEntryProcedureIsCompleted");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CROZRegisterEntryProcedureIsCompletedSpecified {
            get {
                return this.cROZRegisterEntryProcedureIsCompletedFieldSpecified;
            }
            set {
                if ((cROZRegisterEntryProcedureIsCompletedFieldSpecified.Equals(value) != true)) {
                    this.cROZRegisterEntryProcedureIsCompletedFieldSpecified = value;
                    this.OnPropertyChanged("CROZRegisterEntryProcedureIsCompletedSpecified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public List<CROZOpticalArchiveFieldSeventeenImageData> CROZOpticalArchiveFieldSeventeenImageDatas {
            get {
                return this.cROZOpticalArchiveFieldSeventeenImageDatasField;
            }
            set {
                if ((this.cROZOpticalArchiveFieldSeventeenImageDatasField != null)) {
                    if ((cROZOpticalArchiveFieldSeventeenImageDatasField.Equals(value) != true)) {
                        this.cROZOpticalArchiveFieldSeventeenImageDatasField = value;
                        this.OnPropertyChanged("CROZOpticalArchiveFieldSeventeenImageDatas");
                    }
                }
                else {
                    this.cROZOpticalArchiveFieldSeventeenImageDatasField = value;
                    this.OnPropertyChanged("CROZOpticalArchiveFieldSeventeenImageDatas");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CROZPledgeOnClaimsRegistrationEntryNumber {
            get {
                return this.cROZPledgeOnClaimsRegistrationEntryNumberField;
            }
            set {
                if ((this.cROZPledgeOnClaimsRegistrationEntryNumberField != null)) {
                    if ((cROZPledgeOnClaimsRegistrationEntryNumberField.Equals(value) != true)) {
                        this.cROZPledgeOnClaimsRegistrationEntryNumberField = value;
                        this.OnPropertyChanged("CROZPledgeOnClaimsRegistrationEntryNumber");
                    }
                }
                else {
                    this.cROZPledgeOnClaimsRegistrationEntryNumberField = value;
                    this.OnPropertyChanged("CROZPledgeOnClaimsRegistrationEntryNumber");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public CROZDistrainSecuredClaimsRegistrationEntryNumbersData CROZDistrainSecuredClaimsRegistrationEntryNumbersData {
            get {
                return this.cROZDistrainSecuredClaimsRegistrationEntryNumbersDataField;
            }
            set {
                if ((this.cROZDistrainSecuredClaimsRegistrationEntryNumbersDataField != null)) {
                    if ((cROZDistrainSecuredClaimsRegistrationEntryNumbersDataField.Equals(value) != true)) {
                        this.cROZDistrainSecuredClaimsRegistrationEntryNumbersDataField = value;
                        this.OnPropertyChanged("CROZDistrainSecuredClaimsRegistrationEntryNumbersData");
                    }
                }
                else {
                    this.cROZDistrainSecuredClaimsRegistrationEntryNumbersDataField = value;
                    this.OnPropertyChanged("CROZDistrainSecuredClaimsRegistrationEntryNumbersData");
                }
            }
        }
    }
}
