// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ereg.egov.bg/segment/R-1016")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ereg.egov.bg/segment/R-1016", IsNullable=true)]
    public partial class CROZBatchIdentifyingData : InformationObject<CROZBatchIdentifyingData> {
        
        private string cROZParticipantNameField;
        
        private string cROZParticipantIdentificationCodeField;
        
        private CROZParticipantAddressData cROZParticipantAddressDataField;
        
        /// <summary>
        /// CROZBatchIdentifyingData class constructor
        /// </summary>
        public CROZBatchIdentifyingData() {
            this.cROZParticipantAddressDataField = new CROZParticipantAddressData();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CROZParticipantName {
            get {
                return this.cROZParticipantNameField;
            }
            set {
                if ((this.cROZParticipantNameField != null)) {
                    if ((cROZParticipantNameField.Equals(value) != true)) {
                        this.cROZParticipantNameField = value;
                        this.OnPropertyChanged("CROZParticipantName");
                    }
                }
                else {
                    this.cROZParticipantNameField = value;
                    this.OnPropertyChanged("CROZParticipantName");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CROZParticipantIdentificationCode {
            get {
                return this.cROZParticipantIdentificationCodeField;
            }
            set {
                if ((this.cROZParticipantIdentificationCodeField != null)) {
                    if ((cROZParticipantIdentificationCodeField.Equals(value) != true)) {
                        this.cROZParticipantIdentificationCodeField = value;
                        this.OnPropertyChanged("CROZParticipantIdentificationCode");
                    }
                }
                else {
                    this.cROZParticipantIdentificationCodeField = value;
                    this.OnPropertyChanged("CROZParticipantIdentificationCode");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CROZParticipantAddressData CROZParticipantAddressData {
            get {
                return this.cROZParticipantAddressDataField;
            }
            set {
                if ((this.cROZParticipantAddressDataField != null)) {
                    if ((cROZParticipantAddressDataField.Equals(value) != true)) {
                        this.cROZParticipantAddressDataField = value;
                        this.OnPropertyChanged("CROZParticipantAddressData");
                    }
                }
                else {
                    this.cROZParticipantAddressDataField = value;
                    this.OnPropertyChanged("CROZParticipantAddressData");
                }
            }
        }
    }
}
