// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ereg.egov.bg/segment/R-1081")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ereg.egov.bg/segment/R-1081", IsNullable=true)]
    public partial class CROZRegistrationEntryParticipantBasicData : InformationObject<CROZRegistrationEntryParticipantBasicData> {
        
        private string cROZParticipantIdentificationCodeField;
        
        private string cROZParticipantNameField;
        
        private string cROZCityNameField;
        
        private string postCodeField;
        
        private string addressDescriptionField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CROZParticipantIdentificationCode {
            get {
                return this.cROZParticipantIdentificationCodeField;
            }
            set {
                if ((this.cROZParticipantIdentificationCodeField != null)) {
                    if ((cROZParticipantIdentificationCodeField.Equals(value) != true)) {
                        this.cROZParticipantIdentificationCodeField = value;
                        this.OnPropertyChanged("CROZParticipantIdentificationCode");
                    }
                }
                else {
                    this.cROZParticipantIdentificationCodeField = value;
                    this.OnPropertyChanged("CROZParticipantIdentificationCode");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CROZParticipantName {
            get {
                return this.cROZParticipantNameField;
            }
            set {
                if ((this.cROZParticipantNameField != null)) {
                    if ((cROZParticipantNameField.Equals(value) != true)) {
                        this.cROZParticipantNameField = value;
                        this.OnPropertyChanged("CROZParticipantName");
                    }
                }
                else {
                    this.cROZParticipantNameField = value;
                    this.OnPropertyChanged("CROZParticipantName");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CROZCityName {
            get {
                return this.cROZCityNameField;
            }
            set {
                if ((this.cROZCityNameField != null)) {
                    if ((cROZCityNameField.Equals(value) != true)) {
                        this.cROZCityNameField = value;
                        this.OnPropertyChanged("CROZCityName");
                    }
                }
                else {
                    this.cROZCityNameField = value;
                    this.OnPropertyChanged("CROZCityName");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                if ((this.postCodeField != null)) {
                    if ((postCodeField.Equals(value) != true)) {
                        this.postCodeField = value;
                        this.OnPropertyChanged("PostCode");
                    }
                }
                else {
                    this.postCodeField = value;
                    this.OnPropertyChanged("PostCode");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AddressDescription {
            get {
                return this.addressDescriptionField;
            }
            set {
                if ((this.addressDescriptionField != null)) {
                    if ((addressDescriptionField.Equals(value) != true)) {
                        this.addressDescriptionField = value;
                        this.OnPropertyChanged("AddressDescription");
                    }
                }
                else {
                    this.addressDescriptionField = value;
                    this.OnPropertyChanged("AddressDescription");
                }
            }
        }
    }
}
