// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>TechnoLogica.Eservices.InformationObjects</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.Eservices.InformationObjects {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.38968")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ereg.egov.bg/segment/R-1092")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ereg.egov.bg/segment/R-1092", IsNullable=true)]
    public partial class CROZRegistrationEntryCreditorsData : InformationObject<CROZRegistrationEntryCreditorsData> {
        
        private List<CROZRegistrationEntryParticipantBasicData> cROZRegistrationEntryParticipantBasicDatasField;
        
        /// <summary>
        /// CROZRegistrationEntryCreditorsData class constructor
        /// </summary>
        public CROZRegistrationEntryCreditorsData() {
            this.cROZRegistrationEntryParticipantBasicDatasField = new List<CROZRegistrationEntryParticipantBasicData>();
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public List<CROZRegistrationEntryParticipantBasicData> CROZRegistrationEntryParticipantBasicDatas {
            get {
                return this.cROZRegistrationEntryParticipantBasicDatasField;
            }
            set {
                if ((this.cROZRegistrationEntryParticipantBasicDatasField != null)) {
                    if ((cROZRegistrationEntryParticipantBasicDatasField.Equals(value) != true)) {
                        this.cROZRegistrationEntryParticipantBasicDatasField = value;
                        this.OnPropertyChanged("CROZRegistrationEntryParticipantBasicDatas");
                    }
                }
                else {
                    this.cROZRegistrationEntryParticipantBasicDatasField = value;
                    this.OnPropertyChanged("CROZRegistrationEntryParticipantBasicDatas");
                }
            }
        }
    }
}
