//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.Eservices.Common.ExceptionManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnoLogica.Eservices.Common.ExceptionManagement.BusinessErrors", typeof(BusinessErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name:.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка при изпълнение на адаптер: {0}.
        /// </summary>
        public static string AdapterExecutionError {
            get {
                return ResourceManager.GetString("AdapterExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discodb.ad.tlogica.com/adfs/ls/?wa=wsignin1.0&amp;wtrealm=https%3a%2f%2fdev.aiskao.com%2fais%2f&amp;wctx=rm%3d0%26id%3dpassive%26ru%3d%252fais%252f&amp;wct=2013-10-28T14%3a42%3a00Z.
        /// </summary>
        public static string ADFS {
            get {
                return ResourceManager.GetString("ADFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връщане към предишната страница.
        /// </summary>
        public static string BackToPreviousPage {
            get {
                return ResourceManager.GetString("BackToPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Name:.
        /// </summary>
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видът на документа е неизвестен!.
        /// </summary>
        public static string DocTypeNotDefined {
            get {
                return ResourceManager.GetString("DocTypeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурсът който търсите не може да бъде намерен.
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и час на възникване на грешката:.
        /// </summary>
        public static string ErrorDateAndTime {
            get {
                return ResourceManager.GetString("ErrorDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при обработването на вашата заявка.
        /// </summary>
        public static string ErrorOccur {
            get {
                return ResourceManager.GetString("ErrorOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробна техническа информация за грешката.
        /// </summary>
        public static string ErrorTechnicalDetails {
            get {
                return ResourceManager.GetString("ErrorTechnicalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Exception Text:.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществува създадена преписка с документа..
        /// </summary>
        public static string ExistCaseForDocument {
            get {
                return ResourceManager.GetString("ExistCaseForDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при обработка на вашата заявка, проверете данните и опитайте отново!!!.
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Status Code:.
        /// </summary>
        public static string HTTPStatusCode {
            get {
                return ResourceManager.GetString("HTTPStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Status Code Name:.
        /// </summary>
        public static string HTTPStatusCodeName {
            get {
                return ResourceManager.GetString("HTTPStatusCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Нямате права върху страницата която се опитвате да достъпите или функцията!!!&quot;.
        /// </summary>
        public static string InsufficientRights {
            get {
                return ResourceManager.GetString("InsufficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден формат на дата!!! ex: dd.MM.yyyy.
        /// </summary>
        public static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидно ЕГН/ЛНЧ, трябва да съдържа само цифри!!!.
        /// </summary>
        public static string InvalidEgnLnch {
            get {
                return ResourceManager.GetString("InvalidEgnLnch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не съществува такава услуга!.
        /// </summary>
        public static string InvalidServiceType {
            get {
                return ResourceManager.GetString("InvalidServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Target Namespace! Target namespace: {0}.
        /// </summary>
        public static string InvalidTargetNamespace {
            get {
                return ResourceManager.GetString("InvalidTargetNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е зададен отговорник за услугата: {0}.
        /// </summary>
        public static string MissingDefaultUserForServiceType {
            get {
                return ResourceManager.GetString("MissingDefaultUserForServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;ЕИК/код по БУЛСТАТ&quot; в секция &quot;получател на ЕАУ&quot; не е зададено!.
        /// </summary>
        public static string MissingEntityIdentifier {
            get {
                return ResourceManager.GetString("MissingEntityIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето от тип &quot;Наименование на юридическо лице, клон на чуждестранно юридическо лице или едноличен търговец&quot; в секция &quot;получател на ЕАУ&quot; не е зададено!.
        /// </summary>
        public static string MissingEntityName {
            get {
                return ResourceManager.GetString("MissingEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето от тип &quot;Място на раждане на физическо лице, нерегистрирано по българското законодателство&quot; в секция &quot;Заявител на ЕАУ&quot; не е зададено!.
        /// </summary>
        public static string MissingForeignCitizenPlaceOfBirth {
            get {
                return ResourceManager.GetString("MissingForeignCitizenPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето от тип &quot;Държава&quot;  на &quot;Чуждестранно юридическо лице&quot; в секция &quot;получател на ЕАУ&quot; не е зададено!.
        /// </summary>
        public static string MissingForeignEntityCountryData {
            get {
                return ResourceManager.GetString("MissingForeignEntityCountryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липсват данни за уникално идентифициращи чуждестранното юридическо лице  в секция &quot;получател на ЕАУ&quot; - или регистър и номер в регистъра, или други данни!.
        /// </summary>
        public static string MissingForeignEntityIdentifier {
            get {
                return ResourceManager.GetString("MissingForeignEntityIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето от тип &quot;Собствено име&quot; в секция &quot;Заявител на ЕАУ&quot; не е зададено!.
        /// </summary>
        public static string MissingPersonFirstName {
            get {
                return ResourceManager.GetString("MissingPersonFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поне един от полетата от тип &quot;Фамилно име на латиница на физическо лице, нерегистрирано по българското законодателство&quot; или &quot;Други имена на латиница на физическо лице, нерегистрирано по българското законодателство&quot; в секция &quot;Имена на физическо лице, нерегистрирано по българското законодателство&quot; трябва да е зададено!.
        /// </summary>
        public static string MissingPersonLatinNames {
            get {
                return ResourceManager.GetString("MissingPersonLatinNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поне един от полетата от тип &quot;Бащино име&quot; или &quot;Фамилно име&quot; в секция &quot;Заявител на ЕАУ&quot; трябва да е зададено!.
        /// </summary>
        public static string MissingPersonNames {
            get {
                return ResourceManager.GetString("MissingPersonNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При регистриран документ във външен регистър трябва да са зададени Регистров индекс, Пореден номер и Дата.
        /// </summary>
        public static string MissingSequenceNumberOrSigningDateForOuterRegister {
            get {
                return ResourceManager.GetString("MissingSequenceNumberOrSigningDateForOuterRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Намерени са повече от един възможни следващи етапа!.
        /// </summary>
        public static string MoreThanOneStagesFound {
            get {
                return ResourceManager.GetString("MoreThanOneStagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нямате достъп до данните.
        /// </summary>
        public static string NoAccessToData {
            get {
                return ResourceManager.GetString("NoAccessToData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За системни параметри с отбелязана колона на съхранение &quot;None&quot; не е възможно съхранение в базата!.
        /// </summary>
        public static string NoDatabaseStorageIsAllowedForParameterOfTypeNone {
            get {
                return ResourceManager.GetString("NoDatabaseStorageIsAllowedForParameterOfTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е дефинирана XML схема за документа.
        /// </summary>
        public static string NoXMLSchemaDefined {
            get {
                return ResourceManager.GetString("NoXMLSchemaDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържанието на заявлението е празно.
        /// </summary>
        public static string requestDocumentContentCannotBeNull {
            get {
                return ResourceManager.GetString("requestDocumentContentCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избраният период за търсене е твърде дълъг!.
        /// </summary>
        public static string SearchPeriodTooLong {
            get {
                return ResourceManager.GetString("SearchPeriodTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не може да бъде намерена информация за услуга обвързана с подадената задача!.
        /// </summary>
        public static string ServiceInfoCannotBeFound {
            get {
                return ResourceManager.GetString("ServiceInfoCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не може да бъде намерена връзка между тип услуга и етпа!.
        /// </summary>
        public static string ServiceTypeStageCannotBeFoud {
            get {
                return ResourceManager.GetString("ServiceTypeStageCannotBeFoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услугата в момента е недостъпна. Опитайте отново..
        /// </summary>
        public static string ServiceUnavailable {
            get {
                return ResourceManager.GetString("ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трябва да се въведе системния праметър {0}.
        /// </summary>
        public static string SystemParameterNoValue {
            get {
                return ResourceManager.GetString("SystemParameterNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачата е вече приключена!.
        /// </summary>
        public static string TaskAlreadyCompleted {
            get {
                return ResourceManager.GetString("TaskAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестова грешка....
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точно един от аргументите &apos;{0}&apos; и &apos;{1}&apos; може да бъде зададен при регистрация на документ..
        /// </summary>
        public static string TooManyArgumentsInRegisteredDocument {
            get {
                return ResourceManager.GetString("TooManyArgumentsInRegisteredDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липсва структурирано съдържание за един или няколко документа, участващи в трансформацията!.
        /// </summary>
        public static string TransformationDocContentsMissing {
            get {
                return ResourceManager.GetString("TransformationDocContentsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е намерена трансформация!.
        /// </summary>
        public static string TransformationNotFound {
            get {
                return ResourceManager.GetString("TransformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустим MIME формат на файл.
        /// </summary>
        public static string UnknownMimeFormat {
            get {
                return ResourceManager.GetString("UnknownMimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сканирането за вируси не успя да завърши!.
        /// </summary>
        public static string VirusScanNotCompleted {
            get {
                return ResourceManager.GetString("VirusScanNotCompleted", resourceCulture);
            }
        }
    }
}
