//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.Eservices.Common.ExceptionManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyConstrains {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyConstrains() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnoLogica.Eservices.Common.ExceptionManagement.KeyConstrains", typeof(KeyConstrains).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_ADM_BODIES.
        /// </summary>
        internal static string CK_ADM_BODIES {
            get {
                return ResourceManager.GetString("CK_ADM_BODIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_ADM_DEPARTMENT_POSITIONS.
        /// </summary>
        internal static string CK_ADM_DEPARTMENT_POSITIONS {
            get {
                return ResourceManager.GetString("CK_ADM_DEPARTMENT_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_ADM_DEPARTMENTS.
        /// </summary>
        internal static string CK_ADM_DEPARTMENTS {
            get {
                return ResourceManager.GetString("CK_ADM_DEPARTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_ADM_POSITIONS.
        /// </summary>
        internal static string CK_ADM_POSITIONS {
            get {
                return ResourceManager.GetString("CK_ADM_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_CLASS_SCHEME_ACCESS_GRANTS.
        /// </summary>
        internal static string CK_CLASS_SCHEME_ACCESS_GRANTS {
            get {
                return ResourceManager.GetString("CK_CLASS_SCHEME_ACCESS_GRANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_CLASS_SCHEME_ACCESS_GRNTS_G.
        /// </summary>
        internal static string CK_CLASS_SCHEME_ACCESS_GRNTS_G {
            get {
                return ResourceManager.GetString("CK_CLASS_SCHEME_ACCESS_GRNTS_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_DOCUMENTS.
        /// </summary>
        internal static string CK_DOCUMENTS {
            get {
                return ResourceManager.GetString("CK_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За овластени лица трябва да е въведен или Позиция или Потребител.
        /// </summary>
        internal static string CK_EMPOWERED_PERSONS {
            get {
                return ResourceManager.GetString("CK_EMPOWERED_PERSONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_ENTITIES.
        /// </summary>
        internal static string CK_ENTITIES {
            get {
                return ResourceManager.GetString("CK_ENTITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_FOREIGN_CITIZENS_IND_TYPE.
        /// </summary>
        internal static string CK_FOREIGN_CITIZENS_IND_TYPE {
            get {
                return ResourceManager.GetString("CK_FOREIGN_CITIZENS_IND_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_FOREIGN_CITIZENS_LATIN_NAMES.
        /// </summary>
        internal static string CK_FOREIGN_CITIZENS_LATIN_NAMES {
            get {
                return ResourceManager.GetString("CK_FOREIGN_CITIZENS_LATIN_NAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_FOREIGN_ENT_IDENTIFIER.
        /// </summary>
        internal static string CK_FOREIGN_ENT_IDENTIFIER {
            get {
                return ResourceManager.GetString("CK_FOREIGN_ENT_IDENTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_FOREIGN_ENTITIES.
        /// </summary>
        internal static string CK_FOREIGN_ENTITIES {
            get {
                return ResourceManager.GetString("CK_FOREIGN_ENTITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_INDIVIDUALS_NAMES.
        /// </summary>
        internal static string CK_INDIVIDUALS_NAMES {
            get {
                return ResourceManager.GetString("CK_INDIVIDUALS_NAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_INDIVIDUALS_OBJ_TYPE.
        /// </summary>
        internal static string CK_INDIVIDUALS_OBJ_TYPE {
            get {
                return ResourceManager.GetString("CK_INDIVIDUALS_OBJ_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_INDIVIDUALS_TYPE.
        /// </summary>
        internal static string CK_INDIVIDUALS_TYPE {
            get {
                return ResourceManager.GetString("CK_INDIVIDUALS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_LEGAL_ENTITIES.
        /// </summary>
        internal static string CK_LEGAL_ENTITIES {
            get {
                return ResourceManager.GetString("CK_LEGAL_ENTITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_PERSONS.
        /// </summary>
        internal static string CK_PERSONS {
            get {
                return ResourceManager.GetString("CK_PERSONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_REGISTERED_DOCUMENTS_TYPES.
        /// </summary>
        internal static string CK_REGISTERED_DOCUMENTS_TYPES {
            get {
                return ResourceManager.GetString("CK_REGISTERED_DOCUMENTS_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_REGISTERED_FOREIGN_PERSONS.
        /// </summary>
        internal static string CK_REGISTERED_FOREIGN_PERSONS {
            get {
                return ResourceManager.GetString("CK_REGISTERED_FOREIGN_PERSONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_REGISTERS.
        /// </summary>
        internal static string CK_REGISTERS {
            get {
                return ResourceManager.GetString("CK_REGISTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_REGISTERS_INDEX.
        /// </summary>
        internal static string CK_REGISTERS_INDEX {
            get {
                return ResourceManager.GetString("CK_REGISTERS_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_SERVICE_TYPES.
        /// </summary>
        internal static string CK_SERVICE_TYPES {
            get {
                return ResourceManager.GetString("CK_SERVICE_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_SERVICE_TYPES_URI.
        /// </summary>
        internal static string CK_SERVICE_TYPES_URI {
            get {
                return ResourceManager.GetString("CK_SERVICE_TYPES_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_SOLE_TRADERS.
        /// </summary>
        internal static string CK_SOLE_TRADERS {
            get {
                return ResourceManager.GetString("CK_SOLE_TRADERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_STAGE_EXECUTORS.
        /// </summary>
        internal static string CK_STAGE_EXECUTORS {
            get {
                return ResourceManager.GetString("CK_STAGE_EXECUTORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_STAGE_EXECUTORS_MANAGER.
        /// </summary>
        internal static string CK_STAGE_EXECUTORS_MANAGER {
            get {
                return ResourceManager.GetString("CK_STAGE_EXECUTORS_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_TASKS.
        /// </summary>
        internal static string CK_TASKS {
            get {
                return ResourceManager.GetString("CK_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_TASKS_STATUS.
        /// </summary>
        internal static string CK_TASKS_STATUS {
            get {
                return ResourceManager.GetString("CK_TASKS_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_USERS_INDIVIDUAL.
        /// </summary>
        internal static string CK_USERS_INDIVIDUAL {
            get {
                return ResourceManager.GetString("CK_USERS_INDIVIDUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK_USERS_OBJ_TYPE.
        /// </summary>
        internal static string CK_USERS_OBJ_TYPE {
            get {
                return ResourceManager.GetString("CK_USERS_OBJ_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ABROAD_SETTLEMNTS_COUNTRIES.
        /// </summary>
        internal static string FK_ABROAD_SETTLEMNTS_COUNTRIES {
            get {
                return ResourceManager.GetString("FK_ABROAD_SETTLEMNTS_COUNTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ADAPTER_OP_ADAPTER.
        /// </summary>
        internal static string FK_ADAPTER_OP_ADAPTER {
            get {
                return ResourceManager.GetString("FK_ADAPTER_OP_ADAPTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ADAPTER_OP_INPUT_DOC_TYPES.
        /// </summary>
        internal static string FK_ADAPTER_OP_INPUT_DOC_TYPES {
            get {
                return ResourceManager.GetString("FK_ADAPTER_OP_INPUT_DOC_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ADAPTER_OP_OUT_DOC_TYPES.
        /// </summary>
        internal static string FK_ADAPTER_OP_OUT_DOC_TYPES {
            get {
                return ResourceManager.GetString("FK_ADAPTER_OP_OUT_DOC_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В този регион работи административен орган..
        /// </summary>
        internal static string FK_ADM_BODIES_ADM_REGIONS {
            get {
                return ResourceManager.GetString("FK_ADM_BODIES_ADM_REGIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ADM_BODIES_POSITIONS.
        /// </summary>
        internal static string FK_ADM_BODIES_POSITIONS {
            get {
                return ResourceManager.GetString("FK_ADM_BODIES_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В този регион работи административно звено..
        /// </summary>
        internal static string FK_ADM_DEPARTMENTS_ADM_REGIONS {
            get {
                return ResourceManager.GetString("FK_ADM_DEPARTMENTS_ADM_REGIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществува връзка между административни звена.
        /// </summary>
        internal static string FK_ADM_DEPT_ADM_DEPT {
            get {
                return ResourceManager.GetString("FK_ADM_DEPT_ADM_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ADM_DEPT_POS.
        /// </summary>
        internal static string FK_ADM_DEPT_POS {
            get {
                return ResourceManager.GetString("FK_ADM_DEPT_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществува връзка между позиция и административно звено.
        /// </summary>
        internal static string FK_ADM_DEPT_POSITIONS_ADM_DEPT {
            get {
                return ResourceManager.GetString("FK_ADM_DEPT_POSITIONS_ADM_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избраната позиция е част от позициите в административно звено..
        /// </summary>
        internal static string FK_ADM_DEPT_POSITIONS_ADM_POS {
            get {
                return ResourceManager.GetString("FK_ADM_DEPT_POSITIONS_ADM_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ADM_DEPT_POSITIONS_POSITION.
        /// </summary>
        internal static string FK_ADM_DEPT_POSITIONS_POSITION {
            get {
                return ResourceManager.GetString("FK_ADM_DEPT_POSITIONS_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избраният потребител е ръководител на административно звено..
        /// </summary>
        internal static string FK_ADM_DEPT_USERS {
            get {
                return ResourceManager.GetString("FK_ADM_DEPT_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ADM_INFORMATIONS_USERS.
        /// </summary>
        internal static string FK_ADM_INFORMATIONS_USERS {
            get {
                return ResourceManager.GetString("FK_ADM_INFORMATIONS_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ADM_POS_POS.
        /// </summary>
        internal static string FK_ADM_POS_POS {
            get {
                return ResourceManager.GetString("FK_ADM_POS_POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_AUDIT_COLUMNS_TABLES.
        /// </summary>
        internal static string FK_AUDIT_COLUMNS_TABLES {
            get {
                return ResourceManager.GetString("FK_AUDIT_COLUMNS_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_AUDIT_VALUES_AUDIT_RECORDS.
        /// </summary>
        internal static string FK_AUDIT_VALUES_AUDIT_RECORDS {
            get {
                return ResourceManager.GetString("FK_AUDIT_VALUES_AUDIT_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CASE_SEC_ELEMENTS_CASES.
        /// </summary>
        internal static string FK_CASE_SEC_ELEMENTS_CASES {
            get {
                return ResourceManager.GetString("FK_CASE_SEC_ELEMENTS_CASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CASE_SEC_ELEMENTS_DOCUMENTS.
        /// </summary>
        internal static string FK_CASE_SEC_ELEMENTS_DOCUMENTS {
            get {
                return ResourceManager.GetString("FK_CASE_SEC_ELEMENTS_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CASE_SEC_ELEMENTS_REF_CASES.
        /// </summary>
        internal static string FK_CASE_SEC_ELEMENTS_REF_CASES {
            get {
                return ResourceManager.GetString("FK_CASE_SEC_ELEMENTS_REF_CASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CASE_SEC_ELEMENTS_TASKS.
        /// </summary>
        internal static string FK_CASE_SEC_ELEMENTS_TASKS {
            get {
                return ResourceManager.GetString("FK_CASE_SEC_ELEMENTS_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CASE_SECTION_ELEM_EXCLD_BY.
        /// </summary>
        internal static string FK_CASE_SECTION_ELEM_EXCLD_BY {
            get {
                return ResourceManager.GetString("FK_CASE_SECTION_ELEM_EXCLD_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CASE_SECTION_ELEM_INCLD_BY.
        /// </summary>
        internal static string FK_CASE_SECTION_ELEM_INCLD_BY {
            get {
                return ResourceManager.GetString("FK_CASE_SECTION_ELEM_INCLD_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CASES_DOCUMENTS.
        /// </summary>
        internal static string FK_CASES_DOCUMENTS {
            get {
                return ResourceManager.GetString("FK_CASES_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CLASS_SCHEME_GRNTS_POSITION.
        /// </summary>
        internal static string FK_CLASS_SCHEME_GRNTS_POSITION {
            get {
                return ResourceManager.GetString("FK_CLASS_SCHEME_GRNTS_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CLASS_SCHEME_GRNTS_SCHEMES.
        /// </summary>
        internal static string FK_CLASS_SCHEME_GRNTS_SCHEMES {
            get {
                return ResourceManager.GetString("FK_CLASS_SCHEME_GRNTS_SCHEMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CLASS_SCHEME_GRNTS_SECTIONS.
        /// </summary>
        internal static string FK_CLASS_SCHEME_GRNTS_SECTIONS {
            get {
                return ResourceManager.GetString("FK_CLASS_SCHEME_GRNTS_SECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CLASS_SCHEME_GRNTS_USERS.
        /// </summary>
        internal static string FK_CLASS_SCHEME_GRNTS_USERS {
            get {
                return ResourceManager.GetString("FK_CLASS_SCHEME_GRNTS_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_CLASS_SCHEME_SECTION_TYPE.
        /// </summary>
        internal static string FK_CLASS_SCHEME_SECTION_TYPE {
            get {
                return ResourceManager.GetString("FK_CLASS_SCHEME_SECTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_ATTACHMENTS_ATTACHMENT.
        /// </summary>
        internal static string FK_DOC_ATTACHMENTS_ATTACHMENT {
            get {
                return ResourceManager.GetString("FK_DOC_ATTACHMENTS_ATTACHMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_ATTACHMENTS_DOCUMENTS.
        /// </summary>
        internal static string FK_DOC_ATTACHMENTS_DOCUMENTS {
            get {
                return ResourceManager.GetString("FK_DOC_ATTACHMENTS_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_CONTENTS_DOCUMENTS.
        /// </summary>
        internal static string FK_DOC_CONTENTS_DOCUMENTS {
            get {
                return ResourceManager.GetString("FK_DOC_CONTENTS_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_CONTENTS_SIGNER_USERS.
        /// </summary>
        internal static string FK_DOC_CONTENTS_SIGNER_USERS {
            get {
                return ResourceManager.GetString("FK_DOC_CONTENTS_SIGNER_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_DISCREPANCIES_DOCUMENTS.
        /// </summary>
        internal static string FK_DOC_DISCREPANCIES_DOCUMENTS {
            get {
                return ResourceManager.GetString("FK_DOC_DISCREPANCIES_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_DISCREPANCIES_TYPES.
        /// </summary>
        internal static string FK_DOC_DISCREPANCIES_TYPES {
            get {
                return ResourceManager.GetString("FK_DOC_DISCREPANCIES_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_OPINION_AUTHOR.
        /// </summary>
        internal static string FK_DOC_OPINION_AUTHOR {
            get {
                return ResourceManager.GetString("FK_DOC_OPINION_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_OPINION_DOCUMENTS.
        /// </summary>
        internal static string FK_DOC_OPINION_DOCUMENTS {
            get {
                return ResourceManager.GetString("FK_DOC_OPINION_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_OPINION_REF.
        /// </summary>
        internal static string FK_DOC_OPINION_REF {
            get {
                return ResourceManager.GetString("FK_DOC_OPINION_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този вид становище по документ се използва в системата..
        /// </summary>
        internal static string FK_DOC_OPINION_TYPES {
            get {
                return ResourceManager.GetString("FK_DOC_OPINION_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_TYPE_SW_APPL_DOC_TYPES.
        /// </summary>
        internal static string FK_DOC_TYPE_SW_APPL_DOC_TYPES {
            get {
                return ResourceManager.GetString("FK_DOC_TYPE_SW_APPL_DOC_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_TYPE_TEMPLATES_DOC_TYPE.
        /// </summary>
        internal static string FK_DOC_TYPE_TEMPLATES_DOC_TYPE {
            get {
                return ResourceManager.GetString("FK_DOC_TYPE_TEMPLATES_DOC_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_TYPE_XML_SCHEMA_DOC_T.
        /// </summary>
        internal static string FK_DOC_TYPE_XML_SCHEMA_DOC_T {
            get {
                return ResourceManager.GetString("FK_DOC_TYPE_XML_SCHEMA_DOC_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тази архивна стойност на документи се използва в системата..
        /// </summary>
        internal static string FK_DOC_TYPES_ARCHIVAL_TYPES {
            get {
                return ResourceManager.GetString("FK_DOC_TYPES_ARCHIVAL_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOC_TYPES_CLASS_SCHEME_SEC.
        /// </summary>
        internal static string FK_DOC_TYPES_CLASS_SCHEME_SEC {
            get {
                return ResourceManager.GetString("FK_DOC_TYPES_CLASS_SCHEME_SEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този начин на обработка на документи се използва в системата..
        /// </summary>
        internal static string FK_DOC_TYPES_PROCESSING_TYPES {
            get {
                return ResourceManager.GetString("FK_DOC_TYPES_PROCESSING_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото съществуват документи от избрания документен тип.
        /// </summary>
        internal static string FK_DOCUMENTS_DOC_TYPES {
            get {
                return ResourceManager.GetString("FK_DOCUMENTS_DOC_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOCUMENTS_INF_OBJECTS.
        /// </summary>
        internal static string FK_DOCUMENTS_INF_OBJECTS {
            get {
                return ResourceManager.GetString("FK_DOCUMENTS_INF_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този вид документ по отношение на процеса се използва в системата..
        /// </summary>
        internal static string FK_DOCUMENTS_PROCESS_TYPES {
            get {
                return ResourceManager.GetString("FK_DOCUMENTS_PROCESS_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_DOCUMENTS_TASKS.
        /// </summary>
        internal static string FK_DOCUMENTS_TASKS {
            get {
                return ResourceManager.GetString("FK_DOCUMENTS_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_E_SERVICE_APPLICANT_INDIVID.
        /// </summary>
        internal static string FK_E_SERVICE_APPLICANT_INDIVID {
            get {
                return ResourceManager.GetString("FK_E_SERVICE_APPLICANT_INDIVID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_E_SERVICE_APPLICANTS_GROUPS.
        /// </summary>
        internal static string FK_E_SERVICE_APPLICANTS_GROUPS {
            get {
                return ResourceManager.GetString("FK_E_SERVICE_APPLICANTS_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_E_SERVICE_RECIP_ENTITIES.
        /// </summary>
        internal static string FK_E_SERVICE_RECIP_ENTITIES {
            get {
                return ResourceManager.GetString("FK_E_SERVICE_RECIP_ENTITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_E_SERVICE_RECIP_GROUPS.
        /// </summary>
        internal static string FK_E_SERVICE_RECIP_GROUPS {
            get {
                return ResourceManager.GetString("FK_E_SERVICE_RECIP_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_E_SERVICE_RECIP_GROUPS_SRV.
        /// </summary>
        internal static string FK_E_SERVICE_RECIP_GROUPS_SRV {
            get {
                return ResourceManager.GetString("FK_E_SERVICE_RECIP_GROUPS_SRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_E_SERVICE_RECIP_INDIVIDUALS.
        /// </summary>
        internal static string FK_E_SERVICE_RECIP_INDIVIDUALS {
            get {
                return ResourceManager.GetString("FK_E_SERVICE_RECIP_INDIVIDUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_E_SERVICE_REGISTRED_DOCS.
        /// </summary>
        internal static string FK_E_SERVICE_REGISTRED_DOCS {
            get {
                return ResourceManager.GetString("FK_E_SERVICE_REGISTRED_DOCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществуват електронни услуги от избрания вид..
        /// </summary>
        internal static string FK_E_SERVICE_SERVICE_TYPES {
            get {
                return ResourceManager.GetString("FK_E_SERVICE_SERVICE_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_E_SERVICE_TAXES_E_SERVICE.
        /// </summary>
        internal static string FK_E_SERVICE_TAXES_E_SERVICE {
            get {
                return ResourceManager.GetString("FK_E_SERVICE_TAXES_E_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_EMPOWERED_PERSONS_DOC_TYPES.
        /// </summary>
        internal static string FK_EMPOWERED_PERSONS_DOC_TYPES {
            get {
                return ResourceManager.GetString("FK_EMPOWERED_PERSONS_DOC_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото избраната позиция е дефинирана като овластено лице за тип документ.
        /// </summary>
        internal static string FK_EMPOWERED_PERSONS_POSITIONS {
            get {
                return ResourceManager.GetString("FK_EMPOWERED_PERSONS_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото избраният потребител е дефиниран като овластено лице за тип документ.
        /// </summary>
        internal static string FK_EMPOWERED_PERSONS_USERS {
            get {
                return ResourceManager.GetString("FK_EMPOWERED_PERSONS_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_EMPOWERING_DOCS_PERSONS.
        /// </summary>
        internal static string FK_EMPOWERING_DOCS_PERSONS {
            get {
                return ResourceManager.GetString("FK_EMPOWERING_DOCS_PERSONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_EMPOWERING_DOCS_REG_DOCS.
        /// </summary>
        internal static string FK_EMPOWERING_DOCS_REG_DOCS {
            get {
                return ResourceManager.GetString("FK_EMPOWERING_DOCS_REG_DOCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ENTITIES_INF_OBJECTS.
        /// </summary>
        internal static string FK_ENTITIES_INF_OBJECTS {
            get {
                return ResourceManager.GetString("FK_ENTITIES_INF_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ESOED_MESSAGES_E_SERVICES.
        /// </summary>
        internal static string FK_ESOED_MESSAGES_E_SERVICES {
            get {
                return ResourceManager.GetString("FK_ESOED_MESSAGES_E_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ESOED_MESSAGES_MSG_TYPES.
        /// </summary>
        internal static string FK_ESOED_MESSAGES_MSG_TYPES {
            get {
                return ResourceManager.GetString("FK_ESOED_MESSAGES_MSG_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ESOED_MESSAGES_RECIPIENT.
        /// </summary>
        internal static string FK_ESOED_MESSAGES_RECIPIENT {
            get {
                return ResourceManager.GetString("FK_ESOED_MESSAGES_RECIPIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ESOED_MESSAGES_REG_DOCS.
        /// </summary>
        internal static string FK_ESOED_MESSAGES_REG_DOCS {
            get {
                return ResourceManager.GetString("FK_ESOED_MESSAGES_REG_DOCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ESOED_MESSAGES_SENDER.
        /// </summary>
        internal static string FK_ESOED_MESSAGES_SENDER {
            get {
                return ResourceManager.GetString("FK_ESOED_MESSAGES_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ESOED_MSG_CONTENTS_MSG.
        /// </summary>
        internal static string FK_ESOED_MSG_CONTENTS_MSG {
            get {
                return ResourceManager.GetString("FK_ESOED_MSG_CONTENTS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ESOED_MSG_REPEATS_MSG.
        /// </summary>
        internal static string FK_ESOED_MSG_REPEATS_MSG {
            get {
                return ResourceManager.GetString("FK_ESOED_MSG_REPEATS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото съществуват дефинирани условия към избрания вид документ.
        /// </summary>
        internal static string FK_EXPR_DEFS_DOC_TYPES {
            get {
                return ResourceManager.GetString("FK_EXPR_DEFS_DOC_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_EXPR_VALUES_COND_DEF.
        /// </summary>
        internal static string FK_EXPR_VALUES_COND_DEF {
            get {
                return ResourceManager.GetString("FK_EXPR_VALUES_COND_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_EXPR_VALUES_DOCUMENTS.
        /// </summary>
        internal static string FK_EXPR_VALUES_DOCUMENTS {
            get {
                return ResourceManager.GetString("FK_EXPR_VALUES_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_EXPR_VALUES_E_SERVICES.
        /// </summary>
        internal static string FK_EXPR_VALUES_E_SERVICES {
            get {
                return ResourceManager.GetString("FK_EXPR_VALUES_E_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществува нерегистриран чуждестранен гражданин с избраното място на раждане.
        /// </summary>
        internal static string FK_FOREIGN_CITIZENS_ABR_SETTLE {
            get {
                return ResourceManager.GetString("FK_FOREIGN_CITIZENS_ABR_SETTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществува чуждестранно юридическо лице от избраната държава.
        /// </summary>
        internal static string FK_FOREIGN_ENTITIES_COUNTRIES {
            get {
                return ResourceManager.GetString("FK_FOREIGN_ENTITIES_COUNTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_INF_OBJECT_ACCESS_INF_OBJ.
        /// </summary>
        internal static string FK_INF_OBJECT_ACCESS_INF_OBJ {
            get {
                return ResourceManager.GetString("FK_INF_OBJECT_ACCESS_INF_OBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_INF_OBJECT_ACCESS_USERS.
        /// </summary>
        internal static string FK_INF_OBJECT_ACCESS_USERS {
            get {
                return ResourceManager.GetString("FK_INF_OBJECT_ACCESS_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_INF_OBJECT_CLASSIF_INF_OBJ.
        /// </summary>
        internal static string FK_INF_OBJECT_CLASSIF_INF_OBJ {
            get {
                return ResourceManager.GetString("FK_INF_OBJECT_CLASSIF_INF_OBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_INF_OBJECT_CLASSIF_SCH_SECT.
        /// </summary>
        internal static string FK_INF_OBJECT_CLASSIF_SCH_SECT {
            get {
                return ResourceManager.GetString("FK_INF_OBJECT_CLASSIF_SCH_SECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_LOG_RECORDS_USERS.
        /// </summary>
        internal static string FK_LOG_RECORDS_USERS {
            get {
                return ResourceManager.GetString("FK_LOG_RECORDS_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществува връзка между роля и административен орган, длъжност или позиция.
        /// </summary>
        internal static string FK_POSITION_ROLES_POSITIONS {
            get {
                return ResourceManager.GetString("FK_POSITION_ROLES_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществува връзка между административен орган, длъжност или позиция и роля.
        /// </summary>
        internal static string FK_POSITION_ROLES_ROLES {
            get {
                return ResourceManager.GetString("FK_POSITION_ROLES_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_REDEF_EXEC_PREV_SRVC_T_STG.
        /// </summary>
        internal static string FK_REDEF_EXEC_PREV_SRVC_T_STG {
            get {
                return ResourceManager.GetString("FK_REDEF_EXEC_PREV_SRVC_T_STG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_REDEF_EXEC_SRVC_TYPE_STG.
        /// </summary>
        internal static string FK_REDEF_EXEC_SRVC_TYPE_STG {
            get {
                return ResourceManager.GetString("FK_REDEF_EXEC_SRVC_TYPE_STG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_REGISTERED_DOCS_DOCUMENTS.
        /// </summary>
        internal static string FK_REGISTERED_DOCS_DOCUMENTS {
            get {
                return ResourceManager.GetString("FK_REGISTERED_DOCS_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_REGISTERED_DOCS_REGISTER.
        /// </summary>
        internal static string FK_REGISTERED_DOCS_REGISTER {
            get {
                return ResourceManager.GetString("FK_REGISTERED_DOCS_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този вид пренос по електронен път се използва в системата..
        /// </summary>
        internal static string FK_REGISTERED_DOCS_TRANSP_TYPE {
            get {
                return ResourceManager.GetString("FK_REGISTERED_DOCS_TRANSP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_ROLE_PERMISSIONS_OPERATIONS.
        /// </summary>
        internal static string FK_ROLE_PERMISSIONS_OPERATIONS {
            get {
                return ResourceManager.GetString("FK_ROLE_PERMISSIONS_OPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дадената роля има операции свързани с нея.
        /// </summary>
        internal static string FK_ROLE_PERMISSIONS_ROLES {
            get {
                return ResourceManager.GetString("FK_ROLE_PERMISSIONS_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SCHEME_SECTIONS_SCHEMES.
        /// </summary>
        internal static string FK_SCHEME_SECTIONS_SCHEMES {
            get {
                return ResourceManager.GetString("FK_SCHEME_SECTIONS_SCHEMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SCHEME_SECTIONS_SCHEMES_SEC.
        /// </summary>
        internal static string FK_SCHEME_SECTIONS_SCHEMES_SEC {
            get {
                return ResourceManager.GetString("FK_SCHEME_SECTIONS_SCHEMES_SEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SEC_SUB_SEC_SECTIONS.
        /// </summary>
        internal static string FK_SEC_SUB_SEC_SECTIONS {
            get {
                return ResourceManager.GetString("FK_SEC_SUB_SEC_SECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SEC_SUB_SEC_SUB_SECTIONS.
        /// </summary>
        internal static string FK_SEC_SUB_SEC_SUB_SECTIONS {
            get {
                return ResourceManager.GetString("FK_SEC_SUB_SEC_SUB_SECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това дефинирано условие участва в граф за изпълнение на услуга..
        /// </summary>
        internal static string FK_SERV_FLOW_ROUTE_EXPR_DEF {
            get {
                return ResourceManager.GetString("FK_SERV_FLOW_ROUTE_EXPR_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SERVICE_STG_END_RESULT_RES.
        /// </summary>
        internal static string FK_SERVICE_STG_END_RESULT_RES {
            get {
                return ResourceManager.GetString("FK_SERVICE_STG_END_RESULT_RES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SERVICE_STG_END_RESULT_STG.
        /// </summary>
        internal static string FK_SERVICE_STG_END_RESULT_STG {
            get {
                return ResourceManager.GetString("FK_SERVICE_STG_END_RESULT_STG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото избраният етап от услуга е част от етапите на изпълнение на съществуващ вид услуга..
        /// </summary>
        internal static string FK_SERVICE_TYPE_STAGE_SRV_STG {
            get {
                return ResourceManager.GetString("FK_SERVICE_TYPE_STAGE_SRV_STG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото са дефинирани етапи за изпълнение на избрания вид услуга..
        /// </summary>
        internal static string FK_SERVICE_TYPE_STAGE_SRV_TYPE {
            get {
                return ResourceManager.GetString("FK_SERVICE_TYPE_STAGE_SRV_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото съществува услуга, чийто иницииращ вид документ е избрания..
        /// </summary>
        internal static string FK_SERVICE_TYPES_DOCUMENT_TYPE {
            get {
                return ResourceManager.GetString("FK_SERVICE_TYPES_DOCUMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото избраната позиция е дефинирана като отговорно лице за вид услуга..
        /// </summary>
        internal static string FK_SERVICE_TYPES_POSITIONS {
            get {
                return ResourceManager.GetString("FK_SERVICE_TYPES_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SERVICE_TYPES_REG_DOCS.
        /// </summary>
        internal static string FK_SERVICE_TYPES_REG_DOCS {
            get {
                return ResourceManager.GetString("FK_SERVICE_TYPES_REG_DOCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото избраният потребител е дефиниран като отговорно лице за вид услуга..
        /// </summary>
        internal static string FK_SERVICE_TYPES_USERS {
            get {
                return ResourceManager.GetString("FK_SERVICE_TYPES_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SOLE_TRADERS_INDIVIDUALS.
        /// </summary>
        internal static string FK_SOLE_TRADERS_INDIVIDUALS {
            get {
                return ResourceManager.GetString("FK_SOLE_TRADERS_INDIVIDUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този етап участва в граф за изпълнение на услуга..
        /// </summary>
        internal static string FK_SRV_FLOW_ROUTE_CRRNT_STAGE {
            get {
                return ResourceManager.GetString("FK_SRV_FLOW_ROUTE_CRRNT_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този етап участва в граф за изпълнение на услуга..
        /// </summary>
        internal static string FK_SRV_FLOW_ROUTE_NEXT_STAGE {
            get {
                return ResourceManager.GetString("FK_SRV_FLOW_ROUTE_NEXT_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SRV_TYP_RES_RCPT_M_RCPT_MET.
        /// </summary>
        internal static string FK_SRV_TYP_RES_RCPT_M_RCPT_MET {
            get {
                return ResourceManager.GetString("FK_SRV_TYP_RES_RCPT_M_RCPT_MET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SRV_TYP_RES_RCPT_M_SRV_TYPE.
        /// </summary>
        internal static string FK_SRV_TYP_RES_RCPT_M_SRV_TYPE {
            get {
                return ResourceManager.GetString("FK_SRV_TYP_RES_RCPT_M_SRV_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този вид информация, която може да се придава към публичната информация за вид услуга, се използва в системата..
        /// </summary>
        internal static string FK_SRV_TYPE_INF_BITS_BIT_TYPES {
            get {
                return ResourceManager.GetString("FK_SRV_TYPE_INF_BITS_BIT_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дефинирана е публична информация за този вид услуга..
        /// </summary>
        internal static string FK_SRV_TYPE_INF_BITS_TYPES {
            get {
                return ResourceManager.GetString("FK_SRV_TYPE_INF_BITS_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SRV_TYPE_PUB_INFO_TYPES.
        /// </summary>
        internal static string FK_SRV_TYPE_PUB_INFO_TYPES {
            get {
                return ResourceManager.GetString("FK_SRV_TYPE_PUB_INFO_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SRV_TYPE_STG_GROUP_TYPES.
        /// </summary>
        internal static string FK_SRV_TYPE_STG_GROUP_TYPES {
            get {
                return ResourceManager.GetString("FK_SRV_TYPE_STG_GROUP_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този срок за предоставяне на услуга се използва в системата..
        /// </summary>
        internal static string FK_SRV_TYPE_TERM_TYPE_TERM_TYP {
            get {
                return ResourceManager.GetString("FK_SRV_TYPE_TERM_TYPE_TERM_TYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SRV_TYPE_TERM_TYPE_TYPES.
        /// </summary>
        internal static string FK_SRV_TYPE_TERM_TYPE_TYPES {
            get {
                return ResourceManager.GetString("FK_SRV_TYPE_TERM_TYPE_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SRVC_STG_DOC_OR_RES_DOC_TYP.
        /// </summary>
        internal static string FK_SRVC_STG_DOC_OR_RES_DOC_TYP {
            get {
                return ResourceManager.GetString("FK_SRVC_STG_DOC_OR_RES_DOC_TYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тази операция на адаптер е част от операциите на съществуващ етап от услуга. .
        /// </summary>
        internal static string FK_SRVC_STG_OPER_ADAPTER_OPER {
            get {
                return ResourceManager.GetString("FK_SRVC_STG_OPER_ADAPTER_OPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това дефинирано условие е част от условията, дефинирани за съществуваща операция на адаптер към етап от услуга..
        /// </summary>
        internal static string FK_SRVC_STG_OPER_EXPR_DEF {
            get {
                return ResourceManager.GetString("FK_SRVC_STG_OPER_EXPR_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_SRVC_STG_OPER_SRVC_STAGES.
        /// </summary>
        internal static string FK_SRVC_STG_OPER_SRVC_STAGES {
            get {
                return ResourceManager.GetString("FK_SRVC_STG_OPER_SRVC_STAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тази позиция е зададена като изпълнител на съществуващ етап в рамките на услуга.
        /// </summary>
        internal static string FK_STAGE_EXECUTORS_POSITIONS {
            get {
                return ResourceManager.GetString("FK_STAGE_EXECUTORS_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_STAGE_EXECUTORS_TYPE_STAGES.
        /// </summary>
        internal static string FK_STAGE_EXECUTORS_TYPE_STAGES {
            get {
                return ResourceManager.GetString("FK_STAGE_EXECUTORS_TYPE_STAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този потребител е зададен като изпълнител на съществуващ етап в рамките на услуга.
        /// </summary>
        internal static string FK_STAGE_EXECUTORS_USERS {
            get {
                return ResourceManager.GetString("FK_STAGE_EXECUTORS_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_STORED_DOC_ACT_CREATED_BY.
        /// </summary>
        internal static string FK_STORED_DOC_ACT_CREATED_BY {
            get {
                return ResourceManager.GetString("FK_STORED_DOC_ACT_CREATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_STORED_DOC_ACT_INDIVIDUAL.
        /// </summary>
        internal static string FK_STORED_DOC_ACT_INDIVIDUAL {
            get {
                return ResourceManager.GetString("FK_STORED_DOC_ACT_INDIVIDUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_STORED_DOC_ACT_STORED_DOCS.
        /// </summary>
        internal static string FK_STORED_DOC_ACT_STORED_DOCS {
            get {
                return ResourceManager.GetString("FK_STORED_DOC_ACT_STORED_DOCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_STORED_DOCS_REG_DOCS.
        /// </summary>
        internal static string FK_STORED_DOCS_REG_DOCS {
            get {
                return ResourceManager.GetString("FK_STORED_DOCS_REG_DOCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_STORED_DOCS_REGISTERED_BY.
        /// </summary>
        internal static string FK_STORED_DOCS_REGISTERED_BY {
            get {
                return ResourceManager.GetString("FK_STORED_DOCS_REGISTERED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_ASSESS_EXECUTION_TYPES.
        /// </summary>
        internal static string FK_TASK_ASSESS_EXECUTION_TYPES {
            get {
                return ResourceManager.GetString("FK_TASK_ASSESS_EXECUTION_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_ASSESS_PROT_ITEM_PROT.
        /// </summary>
        internal static string FK_TASK_ASSESS_PROT_ITEM_PROT {
            get {
                return ResourceManager.GetString("FK_TASK_ASSESS_PROT_ITEM_PROT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_ASSESS_PRT_ITEM_ASSESS.
        /// </summary>
        internal static string FK_TASK_ASSESS_PRT_ITEM_ASSESS {
            get {
                return ResourceManager.GetString("FK_TASK_ASSESS_PRT_ITEM_ASSESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_ASSESS_TASKS.
        /// </summary>
        internal static string FK_TASK_ASSESS_TASKS {
            get {
                return ResourceManager.GetString("FK_TASK_ASSESS_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_INIT_DOC_TYPE_DOC_TYPE.
        /// </summary>
        internal static string FK_TASK_INIT_DOC_TYPE_DOC_TYPE {
            get {
                return ResourceManager.GetString("FK_TASK_INIT_DOC_TYPE_DOC_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_INIT_DOC_TYPE_TASKS.
        /// </summary>
        internal static string FK_TASK_INIT_DOC_TYPE_TASKS {
            get {
                return ResourceManager.GetString("FK_TASK_INIT_DOC_TYPE_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_INITIAL_DOCS_DOCUMENTS.
        /// </summary>
        internal static string FK_TASK_INITIAL_DOCS_DOCUMENTS {
            get {
                return ResourceManager.GetString("FK_TASK_INITIAL_DOCS_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_INITIAL_DOCS_TASKS.
        /// </summary>
        internal static string FK_TASK_INITIAL_DOCS_TASKS {
            get {
                return ResourceManager.GetString("FK_TASK_INITIAL_DOCS_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тази позиция е зададена като възможен изпълнител на съществуваща задача..
        /// </summary>
        internal static string FK_TASK_POSSIBLE_EXEC_POSITION {
            get {
                return ResourceManager.GetString("FK_TASK_POSSIBLE_EXEC_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_POSSIBLE_EXEC_TASKS.
        /// </summary>
        internal static string FK_TASK_POSSIBLE_EXEC_TASKS {
            get {
                return ResourceManager.GetString("FK_TASK_POSSIBLE_EXEC_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този потребител е зададен като възможен изпълнител на съществуваща задача..
        /// </summary>
        internal static string FK_TASK_POSSIBLE_EXEC_USERS {
            get {
                return ResourceManager.GetString("FK_TASK_POSSIBLE_EXEC_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_RESP_PERSONS_TASKS.
        /// </summary>
        internal static string FK_TASK_RESP_PERSONS_TASKS {
            get {
                return ResourceManager.GetString("FK_TASK_RESP_PERSONS_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този потребител е член на екип по изпълнението на съществуваща задача..
        /// </summary>
        internal static string FK_TASK_RESP_PERSONS_USERS {
            get {
                return ResourceManager.GetString("FK_TASK_RESP_PERSONS_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_STATUSES_STATUS_TYPES.
        /// </summary>
        internal static string FK_TASK_STATUSES_STATUS_TYPES {
            get {
                return ResourceManager.GetString("FK_TASK_STATUSES_STATUS_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASK_STATUSES_TASKS.
        /// </summary>
        internal static string FK_TASK_STATUSES_TASKS {
            get {
                return ResourceManager.GetString("FK_TASK_STATUSES_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASKS_E_SERVICES.
        /// </summary>
        internal static string FK_TASKS_E_SERVICES {
            get {
                return ResourceManager.GetString("FK_TASKS_E_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASKS_EXECUTED_BY.
        /// </summary>
        internal static string FK_TASKS_EXECUTED_BY {
            get {
                return ResourceManager.GetString("FK_TASKS_EXECUTED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото избраният етап от услуга е в процес на изпълнение в рамките на текуща задача..
        /// </summary>
        internal static string FK_TASKS_SERVICE_STAGES {
            get {
                return ResourceManager.GetString("FK_TASKS_SERVICE_STAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този статус на задача се използва в системата..
        /// </summary>
        internal static string FK_TASKS_STATUS_TYPES {
            get {
                return ResourceManager.GetString("FK_TASKS_STATUS_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TASKS_TASKS.
        /// </summary>
        internal static string FK_TASKS_TASKS {
            get {
                return ResourceManager.GetString("FK_TASKS_TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този вид документ е входен вид документ за съществуваща трансформация..
        /// </summary>
        internal static string FK_TRANSF_DOC_TYPES_DOC_TYPES {
            get {
                return ResourceManager.GetString("FK_TRANSF_DOC_TYPES_DOC_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_TRANSF_DOC_TYPES_TRANSF.
        /// </summary>
        internal static string FK_TRANSF_DOC_TYPES_TRANSF {
            get {
                return ResourceManager.GetString("FK_TRANSF_DOC_TYPES_TRANSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това дефинирано условие е част от съществуваща трансформация..
        /// </summary>
        internal static string FK_TRANSFORM_EXPR_DEFINITIONS {
            get {
                return ResourceManager.GetString("FK_TRANSFORM_EXPR_DEFINITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този вид документ е изходен вид документ за съществуваща трансформация..
        /// </summary>
        internal static string FK_TRANSFORMATION_DOC_TYPES {
            get {
                return ResourceManager.GetString("FK_TRANSFORMATION_DOC_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За текущия етап в рамките на услуга са дефинирани трансформации..
        /// </summary>
        internal static string FK_TRANSFORMATION_STAGES {
            get {
                return ResourceManager.GetString("FK_TRANSFORMATION_STAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществува потребител на текущата роля.
        /// </summary>
        internal static string FK_USER_ROLES_ROLES {
            get {
                return ResourceManager.GetString("FK_USER_ROLES_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят е свързан с роля.
        /// </summary>
        internal static string FK_USER_ROLES_USERS {
            get {
                return ResourceManager.GetString("FK_USER_ROLES_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_USER_SIGNATURES_USERS.
        /// </summary>
        internal static string FK_USER_SIGNATURES_USERS {
            get {
                return ResourceManager.GetString("FK_USER_SIGNATURES_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществува потребител, на когото съответства това физическо лице .
        /// </summary>
        internal static string FK_USERS_INDIVIDUALS {
            get {
                return ResourceManager.GetString("FK_USERS_INDIVIDUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK_USERS_INFORMATION_OBJECTS.
        /// </summary>
        internal static string FK_USERS_INFORMATION_OBJECTS {
            get {
                return ResourceManager.GetString("FK_USERS_INFORMATION_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществуват потребители, заемащи тази позиция..
        /// </summary>
        internal static string FK_USERS_POSITIONS {
            get {
                return ResourceManager.GetString("FK_USERS_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такъв раздел от класификационна схема вече съществува..
        /// </summary>
        internal static string PK_CLASS_SCHEME_SECTION_TYPES {
            get {
                return ResourceManager.GetString("PK_CLASS_SCHEME_SECTION_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такъв вид неуспешна проверка вече съществува. .
        /// </summary>
        internal static string PK_DOC_DISCREPANCY_TYPES {
            get {
                return ResourceManager.GetString("PK_DOC_DISCREPANCY_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такъв вид пренос по електронен път вече съществува..
        /// </summary>
        internal static string PK_DOC_E_TRANSPORT_TYPES {
            get {
                return ResourceManager.GetString("PK_DOC_E_TRANSPORT_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такъв вид становище относно документ вече съществува..
        /// </summary>
        internal static string PK_DOC_OPINION_TYPES {
            get {
                return ResourceManager.GetString("PK_DOC_OPINION_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такъв вид документ по отношение на процеса вече съществува..
        /// </summary>
        internal static string PK_DOC_PROCESS_TYPES {
            get {
                return ResourceManager.GetString("PK_DOC_PROCESS_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такава архивна стойност на документи вече съществува..
        /// </summary>
        internal static string PK_DOC_TYPE_ARCHIVAL_TYPES {
            get {
                return ResourceManager.GetString("PK_DOC_TYPE_ARCHIVAL_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такъв вид начин на обработка на документи вече съществува..
        /// </summary>
        internal static string PK_DOC_TYPE_PROCESSING_TYPES {
            get {
                return ResourceManager.GetString("PK_DOC_TYPE_PROCESSING_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такъв вид ЕСОЕД съобщение вече съществува..
        /// </summary>
        internal static string PK_ESOED_MESSAGE_TYPES {
            get {
                return ResourceManager.GetString("PK_ESOED_MESSAGE_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече съществува такъв вид информация, която може да се придава към публичната информация за вид услуга..
        /// </summary>
        internal static string PK_SERVICE_INF_BIT_TYPES {
            get {
                return ResourceManager.GetString("PK_SERVICE_INF_BIT_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такъв начин на получаване на резултат от услуга вече съществува..
        /// </summary>
        internal static string PK_SERVICE_RES_RCPT_METHODS {
            get {
                return ResourceManager.GetString("PK_SERVICE_RES_RCPT_METHODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такъв срок за предоставяне на услуга вече съществува..
        /// </summary>
        internal static string PK_SERVICE_TERM_TYPES {
            get {
                return ResourceManager.GetString("PK_SERVICE_TERM_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такъв вид оценка на изпълнение на задача вече съществува..
        /// </summary>
        internal static string PK_TASK_EXECUTION_ASSESS_TYPES {
            get {
                return ResourceManager.GetString("PK_TASK_EXECUTION_ASSESS_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такъв статус на задача вече съществува..
        /// </summary>
        internal static string PK_TASK_STATUS_TYPES {
            get {
                return ResourceManager.GetString("PK_TASK_STATUS_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече съществува такава операция за текущия адаптер..
        /// </summary>
        internal static string UK_ADAPTER_OPERATIONS {
            get {
                return ResourceManager.GetString("UK_ADAPTER_OPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уникалност по административно звено и ЕКДА.
        /// </summary>
        internal static string UK_ADM_DEPARTMENT_POSITIONS {
            get {
                return ResourceManager.GetString("UK_ADM_DEPARTMENT_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уникалност по код.
        /// </summary>
        internal static string UK_CLASS_SCHEME_SECTION_TYPES {
            get {
                return ResourceManager.GetString("UK_CLASS_SCHEME_SECTION_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уникалност по код и идентификатор.
        /// </summary>
        internal static string UK_CLASS_SCHEME_SECTIONS {
            get {
                return ResourceManager.GetString("UK_CLASS_SCHEME_SECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_CLASS_SCHEMES.
        /// </summary>
        internal static string UK_CLASS_SCHEMES {
            get {
                return ResourceManager.GetString("UK_CLASS_SCHEMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_CONDITION_DEFINITIONS.
        /// </summary>
        internal static string UK_CONDITION_DEFINITIONS {
            get {
                return ResourceManager.GetString("UK_CONDITION_DEFINITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_COUNTRIES.
        /// </summary>
        internal static string UK_COUNTRIES {
            get {
                return ResourceManager.GetString("UK_COUNTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_DOC_ATTACHMENTS.
        /// </summary>
        internal static string UK_DOC_ATTACHMENTS {
            get {
                return ResourceManager.GetString("UK_DOC_ATTACHMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_DOC_DISCREPANCIES.
        /// </summary>
        internal static string UK_DOC_DISCREPANCIES {
            get {
                return ResourceManager.GetString("UK_DOC_DISCREPANCIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_DOC_TYPE_XML_SCHEMAS.
        /// </summary>
        internal static string UK_DOC_TYPE_XML_SCHEMAS {
            get {
                return ResourceManager.GetString("UK_DOC_TYPE_XML_SCHEMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_ENTITIES.
        /// </summary>
        internal static string UK_ENTITIES {
            get {
                return ResourceManager.GetString("UK_ENTITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_INDIVIDUALS.
        /// </summary>
        internal static string UK_INDIVIDUALS {
            get {
                return ResourceManager.GetString("UK_INDIVIDUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_INF_OBJECTS.
        /// </summary>
        internal static string UK_INF_OBJECTS {
            get {
                return ResourceManager.GetString("UK_INF_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_POSITIONS.
        /// </summary>
        internal static string UK_POSITIONS {
            get {
                return ResourceManager.GetString("UK_POSITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_principal_name.
        /// </summary>
        internal static string UK_principal_name {
            get {
                return ResourceManager.GetString("UK_principal_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този регистров индекс вече се използва! Моля, въведете нов..
        /// </summary>
        internal static string UK_REGISTERS_INDEX {
            get {
                return ResourceManager.GetString("UK_REGISTERS_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_SCHEME_SECTIONS.
        /// </summary>
        internal static string UK_SCHEME_SECTIONS {
            get {
                return ResourceManager.GetString("UK_SCHEME_SECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_SECTION_SUB_SECTIONS.
        /// </summary>
        internal static string UK_SECTION_SUB_SECTIONS {
            get {
                return ResourceManager.GetString("UK_SECTION_SUB_SECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вече има създаден преход между избраните етапи.
        /// </summary>
        internal static string UK_SERVICE_FLOW_ROUTE {
            get {
                return ResourceManager.GetString("UK_SERVICE_FLOW_ROUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_SERVICE_STAGE_END_RESULTS.
        /// </summary>
        internal static string UK_SERVICE_STAGE_END_RESULTS {
            get {
                return ResourceManager.GetString("UK_SERVICE_STAGE_END_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK_SERVICE_STAGE_GROUP_TYPES.
        /// </summary>
        internal static string UK_SERVICE_STAGE_GROUP_TYPES {
            get {
                return ResourceManager.GetString("UK_SERVICE_STAGE_GROUP_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото вече е дефинирана такава операция на адаптер за текущия етап на услуга..
        /// </summary>
        internal static string UK_SERVICE_STAGE_OPERATIONS {
            get {
                return ResourceManager.GetString("UK_SERVICE_STAGE_OPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото вече съществува такъв етап в рамките на текущата услуга..
        /// </summary>
        internal static string UK_SERVICE_TYPE_STAGES {
            get {
                return ResourceManager.GetString("UK_SERVICE_TYPE_STAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този системен параметър вече съществува! Моля, въведете нов..
        /// </summary>
        internal static string UK_SYSTEM_PARAMETERS {
            get {
                return ResourceManager.GetString("UK_SYSTEM_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото вече съществува такъв служител в екипа по изпълнение..
        /// </summary>
        internal static string UK_TASK_RESPONSIBLE_PERSONS {
            get {
                return ResourceManager.GetString("UK_TASK_RESPONSIBLE_PERSONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действието не може да бъде извършено, защото вече съществува такъв срок за предоставяне на услугата..
        /// </summary>
        internal static string UK_WEB_SRVC_TYPE_TERM_TYPES {
            get {
                return ResourceManager.GetString("UK_WEB_SRVC_TYPE_TERM_TYPES", resourceCulture);
            }
        }
    }
}
