//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.Eservices.Common.ExceptionManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_RECORDS
    {
        public int ID { get; set; }
        public System.DateTime TIME_STAMP { get; set; }
        public int ACTOR_ID { get; set; }
        public string HOST { get; set; }
        public string TYPE { get; set; }
        public string SOURCE { get; set; }
        public string MESSAGE { get; set; }
        public string LOG_LEVEL { get; set; }
        public string LOGGER { get; set; }
        public string STACKTRACE { get; set; }
        public string ALL_XML { get; set; }
    }
}
