//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.Eservices.Public.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_SRVC_TYPE_PUBLIC_INFO
    {
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMPETENT_AUTHORITY { get; set; }
        public string APPLICANT { get; set; }
        public string PAYMENT_AND_TERM_DESCRIPTION { get; set; }
        public string SERVICE_RESPONSIBLE { get; set; }
        public string REFUSAL_APPEAL_PROCEDURE_DESCR { get; set; }
        public string RESULT_DESCRIPTION { get; set; }
        public bool IS_PUBLIC { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public int CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_ON { get; set; }
        public Nullable<int> LAST_MODIFIED_BY { get; set; }
    }
}
