//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.Eservices.Public.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_SERVICE_STAGES_V
    {
        public int SERVICE_ID { get; set; }
        public string TASK_NAME { get; set; }
        public Nullable<System.DateTime> ACTUAL_START_DATE { get; set; }
        public Nullable<System.DateTime> ACTUAL_COMPLETION_DATE { get; set; }
        public string STAGE_NAME { get; set; }
        public System.DateTime INCLUDED_ON { get; set; }
        public Nullable<int> STAGE_STATUS { get; set; }
    }
}
