//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.Eservices.Public.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_USERS_V
    {
        public int ID { get; set; }
        public string NAME { get; set; }
    }
}
