//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.Eservices.Public.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_SRVC_TYPE_INF_BITS
    {
        public int ID { get; set; }
        public int SERVICE_TYPE_ID { get; set; }
        public string SERVICE_INF_BIT_TYPE_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public int APPEARANCE_ORDER { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public int CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_ON { get; set; }
        public Nullable<int> LAST_MODIFIED_BY { get; set; }
    
        public virtual WEB_SRVC_INF_BIT_TYPES WEB_SRVC_INF_BIT_TYPES { get; set; }
    }
}
