//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.Eservices.Public.Site.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Service {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Service() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnoLogica.Eservices.Public.Site.Resources.Service", typeof(Service).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявител.
        /// </summary>
        public static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компетентен орган.
        /// </summary>
        public static string CompetentAuthority {
            get {
                return ResourceManager.GetString("CompetentAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изискване към документите.
        /// </summary>
        public static string DocumentRequirement {
            get {
                return ResourceManager.GetString("DocumentRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Намерени услуги.
        /// </summary>
        public static string FindedServicesTitle {
            get {
                return ResourceManager.GetString("FindedServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за услуга.
        /// </summary>
        public static string GetServiceDetailsTitle {
            get {
                return ResourceManager.GetString("GetServiceDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вътрешен ход на административната услуга.
        /// </summary>
        public static string InternalStep {
            get {
                return ResourceManager.GetString("InternalStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правно основание.
        /// </summary>
        public static string LegalBasis {
            get {
                return ResourceManager.GetString("LegalBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такса и срок.
        /// </summary>
        public static string PaymentAndTermDescription {
            get {
                return ResourceManager.GetString("PaymentAndTermDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация за плащане.
        /// </summary>
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процедура.
        /// </summary>
        public static string Procedure {
            get {
                return ResourceManager.GetString("Procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ред за обжалване.
        /// </summary>
        public static string RefusalAppealProcedureDescription {
            get {
                return ResourceManager.GetString("RefusalAppealProcedureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начини за подаване на електронни документи.
        /// </summary>
        public static string RequestMethod {
            get {
                return ResourceManager.GetString("RequestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходим документ.
        /// </summary>
        public static string RequiredDocument {
            get {
                return ResourceManager.GetString("RequiredDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резултат.
        /// </summary>
        public static string ResultDesription {
            get {
                return ResourceManager.GetString("ResultDesription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене на услуга.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристика.
        /// </summary>
        public static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли.
        /// </summary>
        public static string ServiceDetailToolTip {
            get {
                return ResourceManager.GetString("ServiceDetailToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование на административната услуга.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отговорно лице.
        /// </summary>
        public static string ServiceResponsible {
            get {
                return ResourceManager.GetString("ServiceResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подай заявление.
        /// </summary>
        public static string SubmitDocumentToolTip {
            get {
                return ResourceManager.GetString("SubmitDocumentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УРИ.
        /// </summary>
        public static string URI {
            get {
                return ResourceManager.GetString("URI", resourceCulture);
            }
        }
    }
}
