//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.Eservices.InformationObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnoLogica.Eservices.InformationObjects.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид трансформация на документ.
        /// </summary>
        public static string DocumentTransformationType {
            get {
                return ResourceManager.GetString("DocumentTransformationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        public static string DocumentTransformationTypeDocument {
            get {
                return ResourceManager.GetString("DocumentTransformationTypeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За редакция.
        /// </summary>
        public static string DocumentTransformationTypeHTMLEdit {
            get {
                return ResourceManager.GetString("DocumentTransformationTypeHTMLEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За визуализация.
        /// </summary>
        public static string DocumentTransformationTypeHTMLView {
            get {
                return ResourceManager.GetString("DocumentTransformationTypeHTMLView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка за RegiX.
        /// </summary>
        public static string DocumentTransformationTypeRegiXRequest {
            get {
                return ResourceManager.GetString("DocumentTransformationTypeRegiXRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид съобщение, пренасяно през ЕСОЕД.
        /// </summary>
        public static string ESOEDMessageType {
            get {
                return ResourceManager.GetString("ESOEDMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка, установена от КК.
        /// </summary>
        public static string ESOEDMessageTypeCCError {
            get {
                return ResourceManager.GetString("ESOEDMessageTypeCCError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        public static string ESOEDMessageTypeDocument {
            get {
                return ResourceManager.GetString("ESOEDMessageTypeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждение за получаване в АИС на получателя.
        /// </summary>
        public static string ESOEDMessageTypeDocumentReceipt {
            get {
                return ResourceManager.GetString("ESOEDMessageTypeDocumentReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка, установена от ЕСОЕД.
        /// </summary>
        public static string ESOEDMessageTypeEsoedError {
            get {
                return ResourceManager.GetString("ESOEDMessageTypeEsoedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждение за получаване в ЕСОЕД.
        /// </summary>
        public static string ESOEDMessageTypeEsoedResponse {
            get {
                return ResourceManager.GetString("ESOEDMessageTypeEsoedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестен.
        /// </summary>
        public static string ESOEDMessageTypeUnknown {
            get {
                return ResourceManager.GetString("ESOEDMessageTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to букви на кирилица и символите интервал, ‘ (апостроф) и – (тире).
        /// </summary>
        public static string PersonFirstNameCharsAllowed {
            get {
                return ResourceManager.GetString("PersonFirstNameCharsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to букви на кирилица и символите интервал, ‘ (апостроф) и – (тире).
        /// </summary>
        public static string PersonLastNameCharsAllowed {
            get {
                return ResourceManager.GetString("PersonLastNameCharsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  букви на кирилица и символите интервал, ‘ (апостроф) и – (тире).
        /// </summary>
        public static string PersonMiddleNameCharsAllowed {
            get {
                return ResourceManager.GetString("PersonMiddleNameCharsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to букви на кирилица и символите интервал, ‘ (апостроф) и – (тире).
        /// </summary>
        public static string PersonPseudonimCharsAllowed {
            get {
                return ResourceManager.GetString("PersonPseudonimCharsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изискване към документите.
        /// </summary>
        public static string ServiceInformationBitTypeDocumentRequirement {
            get {
                return ResourceManager.GetString("ServiceInformationBitTypeDocumentRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вътрешен ход на административната услуга.
        /// </summary>
        public static string ServiceInformationBitTypeInternalStep {
            get {
                return ResourceManager.GetString("ServiceInformationBitTypeInternalStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правно основание.
        /// </summary>
        public static string ServiceInformationBitTypeLegalBasis {
            get {
                return ResourceManager.GetString("ServiceInformationBitTypeLegalBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация за плащане.
        /// </summary>
        public static string ServiceInformationBitTypePaymentInformation {
            get {
                return ResourceManager.GetString("ServiceInformationBitTypePaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начини за подаване на електронни документи.
        /// </summary>
        public static string ServiceInformationBitTypeRequestMethod {
            get {
                return ResourceManager.GetString("ServiceInformationBitTypeRequestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходим документ.
        /// </summary>
        public static string ServiceInformationBitTypeRequiredDocument {
            get {
                return ResourceManager.GetString("ServiceInformationBitTypeRequiredDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начин за заявяване на услуга.
        /// </summary>
        public static string ServiceStageExternalServiceType {
            get {
                return ResourceManager.GetString("ServiceStageExternalServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чрез RegiX.
        /// </summary>
        public static string ServiceStageExternalServiceTypeREGIX {
            get {
                return ResourceManager.GetString("ServiceStageExternalServiceTypeREGIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чрез ЕСОЕД.
        /// </summary>
        public static string ServiceStageExternalServiceTypeUEEED {
            get {
                return ResourceManager.GetString("ServiceStageExternalServiceTypeUEEED", resourceCulture);
            }
        }
    }
}
