//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.Eservices.InformationObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Nomenclatures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Nomenclatures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnoLogica.Eservices.InformationObjects.Resources.Nomenclatures", typeof(Nomenclatures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на видовете пренос по електронен път.
        /// </summary>
        public static string _0007_000001 {
            get {
                return ResourceManager.GetString("0007-000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на неуспешните проверки при заявление, подадено по електронен път.
        /// </summary>
        public static string _0007_000002 {
            get {
                return ResourceManager.GetString("0007-000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на видовете доставчици на електронни административни услуги.
        /// </summary>
        public static string _0007_000003 {
            get {
                return ResourceManager.GetString("0007-000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на начините за удостоверяване на правото на достъп на потребител.
        /// </summary>
        public static string _0007_000004 {
            get {
                return ResourceManager.GetString("0007-000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на видовете раздели от класификационна схема.
        /// </summary>
        public static string _0007_000005 {
            get {
                return ResourceManager.GetString("0007-000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на начините на обработка на документите в АИС.
        /// </summary>
        public static string _0007_000006 {
            get {
                return ResourceManager.GetString("0007-000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на архивните стойности на документите в АИС.
        /// </summary>
        public static string _0007_000007 {
            get {
                return ResourceManager.GetString("0007-000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на статусите на задача.
        /// </summary>
        public static string _0007_000008 {
            get {
                return ResourceManager.GetString("0007-000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на видовете оценки на изпълнение на задача.
        /// </summary>
        public static string _0007_000009 {
            get {
                return ResourceManager.GetString("0007-000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на видовете документи по отношение на процеса.
        /// </summary>
        public static string _0007_000011 {
            get {
                return ResourceManager.GetString("0007-000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на видовете становища по документ в АИС.
        /// </summary>
        public static string _0007_000012 {
            get {
                return ResourceManager.GetString("0007-000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на видовете услуги, спрямо срока за предоставянето им.
        /// </summary>
        public static string _0007_000014 {
            get {
                return ResourceManager.GetString("0007-000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на видовете заявления според обстоятелството дали заявлението се подава за първи път или е последващ документ.
        /// </summary>
        public static string _0007_000015 {
            get {
                return ResourceManager.GetString("0007-000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на видовете недвижими имоти по чл. 23 ЗКИР.
        /// </summary>
        public static string _0007_000022 {
            get {
                return ResourceManager.GetString("0007-000022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заключен.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура на видовете обработка на услуга.
        /// </summary>
        public static string R9071 {
            get {
                return ResourceManager.GetString("R9071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключен.
        /// </summary>
        public static string UnLocked {
            get {
                return ResourceManager.GetString("UnLocked", resourceCulture);
            }
        }
    }
}
