//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.Eservices.InformationObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Visualisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Visualisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnoLogica.Eservices.InformationObjects.Resources.Visualisation", typeof(Visualisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид на доставчик.
        /// </summary>
        public static string _0009_000002_ElectronicServiceProviderType {
            get {
                return ResourceManager.GetString("0009-000002_ElectronicServiceProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕИК/БУЛСТАТ.
        /// </summary>
        public static string _0009_000013_Identifier {
            get {
                return ResourceManager.GetString("0009-000013_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string _0009_000013_Name {
            get {
                return ResourceManager.GetString("0009-000013_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държава.
        /// </summary>
        public static string _0009_000014_CountryNameCyrillic {
            get {
                return ResourceManager.GetString("0009-000014_CountryNameCyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string _0009_000014_ForeignEntityName {
            get {
                return ResourceManager.GetString("0009-000014_ForeignEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер в регистър.
        /// </summary>
        public static string _0009_000014_Identifier {
            get {
                return ResourceManager.GetString("0009-000014_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Други данни.
        /// </summary>
        public static string _0009_000014_OtherData {
            get {
                return ResourceManager.GetString("0009-000014_OtherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на регистър.
        /// </summary>
        public static string _0009_000014_Register {
            get {
                return ResourceManager.GetString("0009-000014_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна поща.
        /// </summary>
        public static string _0009_000016_EmailAddress {
            get {
                return ResourceManager.GetString("0009-000016_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст на грешката.
        /// </summary>
        public static string _0009_000024_ErrorDescription {
            get {
                return ResourceManager.GetString("0009-000024_ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УРИ на термин, с който се представя грешката.
        /// </summary>
        public static string _0009_000024_TermURI {
            get {
                return ResourceManager.GetString("0009-000024_TermURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование на проверяван документ.
        /// </summary>
        public static string _0009_000025_DocumentTypeName {
            get {
                return ResourceManager.GetString("0009-000025_DocumentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УРИ на проверяван документ.
        /// </summary>
        public static string _0009_000025_DocumentTypeURI {
            get {
                return ResourceManager.GetString("0009-000025_DocumentTypeURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на тип документ.
        /// </summary>
        public static string _0009_000092_DocumentTypeName {
            get {
                return ResourceManager.GetString("0009-000092_DocumentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УРИ на тип документ.
        /// </summary>
        public static string _0009_000092_DocumentTypeURI {
            get {
                return ResourceManager.GetString("0009-000092_DocumentTypeURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string _0009_000137_AddressDescription {
            get {
                return ResourceManager.GetString("0009-000137_AddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код на област.
        /// </summary>
        public static string _0009_000137_DistrictCode {
            get {
                return ResourceManager.GetString("0009-000137_DistrictCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Област.
        /// </summary>
        public static string _0009_000137_DistrictName {
            get {
                return ResourceManager.GetString("0009-000137_DistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код на община.
        /// </summary>
        public static string _0009_000137_MunicipalityCode {
            get {
                return ResourceManager.GetString("0009-000137_MunicipalityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Община.
        /// </summary>
        public static string _0009_000137_MunicipalityName {
            get {
                return ResourceManager.GetString("0009-000137_MunicipalityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пощенски код.
        /// </summary>
        public static string _0009_000137_PostCode {
            get {
                return ResourceManager.GetString("0009-000137_PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пощенска кутия.
        /// </summary>
        public static string _0009_000137_PostOfficeBox {
            get {
                return ResourceManager.GetString("0009-000137_PostOfficeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код на населено място.
        /// </summary>
        public static string _0009_000137_SettlementCode {
            get {
                return ResourceManager.GetString("0009-000137_SettlementCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Населено място.
        /// </summary>
        public static string _0009_000137_SettlementName {
            get {
                return ResourceManager.GetString("0009-000137_SettlementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string _0009_000139_AttachedDocumentDescription {
            get {
                return ResourceManager.GetString("0009-000139_AttachedDocumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string _0009_000139_AttachedDocumentFileName {
            get {
                return ResourceManager.GetString("0009-000139_AttachedDocumentFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уникален идентификатор.
        /// </summary>
        public static string _0009_000139_AttachedDocumentUniqueIdentifier {
            get {
                return ResourceManager.GetString("0009-000139_AttachedDocumentUniqueIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат.
        /// </summary>
        public static string _0009_000139_FileType {
            get {
                return ResourceManager.GetString("0009-000139_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string _0009_000141_AddressDescription {
            get {
                return ResourceManager.GetString("0009-000141_AddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пощенски код.
        /// </summary>
        public static string _0009_000141_PostCode {
            get {
                return ResourceManager.GetString("0009-000141_PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пощенска кутия.
        /// </summary>
        public static string _0009_000141_PostOfficeBox {
            get {
                return ResourceManager.GetString("0009-000141_PostOfficeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начин на получаване на резултат от услуга.
        /// </summary>
        public static string _0009_000141_ServiceResultReceiptMethod {
            get {
                return ResourceManager.GetString("0009-000141_ServiceResultReceiptMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид заявление.
        /// </summary>
        public static string _0009_000152_ApplicationType {
            get {
                return ResourceManager.GetString("0009-000152_ApplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип документ.
        /// </summary>
        public static string _0009_000152_DocumentTypeName {
            get {
                return ResourceManager.GetString("0009-000152_DocumentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желая да получа документа &quot;Потвърждение за получаване&quot;.
        /// </summary>
        public static string _0009_000152_SendApplicationWithReceiptAcknowledgedMessage {
            get {
                return ResourceManager.GetString("0009-000152_SendApplicationWithReceiptAcknowledgedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Административна услуга.
        /// </summary>
        public static string _0009_000152_SUNAUServiceName {
            get {
                return ResourceManager.GetString("0009-000152_SUNAUServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Време на подписване на заявлението.
        /// </summary>
        public static string _0009_000153_ApplicationSigningTime {
            get {
                return ResourceManager.GetString("0009-000153_ApplicationSigningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на издаване.
        /// </summary>
        public static string _0009_000199_IssueDate {
            get {
                return ResourceManager.GetString("0009-000199_IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер на акт.
        /// </summary>
        public static string _0009_000199_Number {
            get {
                return ResourceManager.GetString("0009-000199_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на издаване.
        /// </summary>
        public static string _0009_000200_IssueDate {
            get {
                return ResourceManager.GetString("0009-000200_IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер на акт.
        /// </summary>
        public static string _0009_000200_Number {
            get {
                return ResourceManager.GetString("0009-000200_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string _0009_000201_NeighboringPropertyDescription {
            get {
                return ResourceManager.GetString("0009-000201_NeighboringPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посока.
        /// </summary>
        public static string _0009_000201_NeighboringPropertyDirection {
            get {
                return ResourceManager.GetString("0009-000201_NeighboringPropertyDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площ на недвижим имот по документи в кв. м..
        /// </summary>
        public static string _0009_000202_AccordingToDocumentsQuadrature {
            get {
                return ResourceManager.GetString("0009-000202_AccordingToDocumentsQuadrature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допълнителна информация.
        /// </summary>
        public static string _0009_000202_RealEstateAdditionalInformation {
            get {
                return ResourceManager.GetString("0009-000202_RealEstateAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес на имот.
        /// </summary>
        public static string _0009_000202_RealEstateAddress {
            get {
                return ResourceManager.GetString("0009-000202_RealEstateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер на партида.
        /// </summary>
        public static string _0009_000202_RealEstateBatchNumber {
            get {
                return ResourceManager.GetString("0009-000202_RealEstateBatchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид имот.
        /// </summary>
        public static string _0009_000202_RealEstateType {
            get {
                return ResourceManager.GetString("0009-000202_RealEstateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реална площ на недвижим имот в кв. м..
        /// </summary>
        public static string _0009_000202_RealQuadrature {
            get {
                return ResourceManager.GetString("0009-000202_RealQuadrature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид на услугата.
        /// </summary>
        public static string _0009_000204_ServiceTermType {
            get {
                return ResourceManager.GetString("0009-000204_ServiceTermType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор/и на електронното изявление:
        ///:Author:
        ///Получател/и на електронната административна услуга:
        ///:Recipient:
        ///Качество, в което авторът действа от името на титуляра и обем на представителната власт:
        ///:AuthorQuality:
        ///Адрес на електронна поща за получаване на електронни изявления:
        ///:EmailAddress:.
        /// </summary>
        public static string ElectronicServiceApplicantDifferentAuthorAndRecipient {
            get {
                return ResourceManager.GetString("ElectronicServiceApplicantDifferentAuthorAndRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получател/и на електронната административна услуга:
        ///:Recipient:
        ///Адрес на електронна поща за получаване на електронни изявления:
        ///:EmailAddress:.
        /// </summary>
        public static string ElectronicServiceApplicantSamAuthorAndRecipient {
            get {
                return ResourceManager.GetString("ElectronicServiceApplicantSamAuthorAndRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не е посочено.
        /// </summary>
        public static string EmptyAuthorQuality {
            get {
                return ResourceManager.GetString("EmptyAuthorQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp &amp;nbsp Основание на овластяването: :AuthorQuality:&lt;br/&gt;.
        /// </summary>
        public static string HtmlAuthorQuality {
            get {
                return ResourceManager.GetString("HtmlAuthorQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Автор/и на електронното изявление:&lt;br/&gt;
        ///:Author:
        ///&lt;/p&gt;
        ///&lt;p&gt;Получател/и на електронната административна услуга:&lt;br/&gt;
        ///:Recipient:
        ///&lt;/p&gt;
        ///&lt;p&gt;Качество, в което авторът действа от името на титуляра и обем на представителната власт:&lt;br/&gt;
        ///:AuthorQuality:
        ///&lt;/p&gt;
        ///&lt;p&gt;Адрес на електронна поща за получаване на електронни изявления:&lt;br/&gt;
        ///:EmailAddress:
        ///&lt;/p&gt;.
        /// </summary>
        public static string HtmlElectronicServiceApplicantDifferentAuthorAndRecipient {
            get {
                return ResourceManager.GetString("HtmlElectronicServiceApplicantDifferentAuthorAndRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Получател/и на електронната административна услуга:&lt;br/&gt;
        ///:Recipient:
        ///&lt;/p&gt;
        ///&lt;p&gt;Адрес на електронна поща за получаване на електронни изявления:&lt;br/&gt;
        ///:EmailAddress:
        ///&lt;/p&gt;.
        /// </summary>
        public static string HtmlElectronicServiceApplicantSamAuthorAndRecipient {
            get {
                return ResourceManager.GetString("HtmlElectronicServiceApplicantSamAuthorAndRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp &amp;nbsp ЕГН или ЕИК на доставчика на удостоверителни услуги: :IssuerBulstat: &lt;br/&gt;.
        /// </summary>
        public static string HtmlIssuerBulstat {
            get {
                return ResourceManager.GetString("HtmlIssuerBulstat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Доставчик на електронни административни услуги:&lt;/b&gt;&lt;br/&gt;
        ///:ElectronicServiceProvider:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Уникален регистров идентификатор на получения документ:&lt;/b&gt;&lt;br/&gt;
        ///:DocumentURI:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Вид на пренос:&lt;/b&gt;&lt;br/&gt;
        ///:TransportType:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Заявител на електронната административна услуга:&lt;/b&gt;&lt;br/&gt;
        ///:Applicant:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Подаден документ:&lt;/b&gt;&lt;br/&gt;
        ///УРИ в регистъра на информационните обекти :DocumentTypeURI:, :DocumentTypeName:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Извършил регистрация [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HtmlReceiptAcknowledgedMessage {
            get {
                return ResourceManager.GetString("HtmlReceiptAcknowledgedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Доставчик на електронни административни услуги:&lt;/b&gt;&lt;br/&gt;
        ///:ElectronicServiceProvider:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Уникален регистров идентификатор на регистриран документ:&lt;/b&gt;&lt;br/&gt;
        ///:DocumentURI:::ElectronicServiceProvider: 
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Вид на пренос:&lt;/b&gt;&lt;br/&gt;
        ///:TransportType:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Получаването не се потвърждава:&lt;/b&gt;&lt;br/&gt;
        ///:Discrepancies:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Заявител на електронната административна услуга:&lt;/b&gt;&lt;br/&gt;
        ///:Applicant:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Подаден документ:&lt;/b&gt;&lt;br/&gt;
        ///УРИ в регис [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HtmlReceiptNotAcknowledgedMessage {
            get {
                return ResourceManager.GetString("HtmlReceiptNotAcknowledgedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Данни за доставчика на удостоверителни услуги: &lt;br/&gt;
        ///&amp;nbsp &amp;nbsp Наименование: :IssuerNameCommonName: ,&lt;br/&gt;
        ///&amp;nbsp &amp;nbsp Адрес: :IssuerAddress: ,&lt;br/&gt;
        ///:IssuerBulstat:
        ///&amp;nbsp &amp;nbsp Националност: :IssuerCountry: 
        ///&lt;/p&gt;
        ///&lt;p&gt;Данни за титуляра на усъвършенствания електронен подпис: &lt;br/&gt;
        ///&amp;nbsp &amp;nbsp Име или наименование: :TitularName: ; &lt;br/&gt;
        ///&amp;nbsp &amp;nbsp Адрес: :TitularAddress: ; &lt;br/&gt;
        ///&amp;nbsp &amp;nbsp Данни за регистрацията на титуляра на усъвършенствания електронен подпис: :TitularOrgCourtRegistration: ; &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HtmlSignature {
            get {
                return ResourceManager.GetString("HtmlSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Наименование:&lt;/b&gt;&lt;br/&gt;
        ///:TaskName:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Описание:&lt;/b&gt;&lt;br/&gt;
        ///:TaskDescription:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Планиран от:&lt;/b&gt;&lt;br/&gt;
        ///:TaskFrom:
        ///&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;&lt;b&gt;Планиран за:&lt;/b&gt;&lt;br/&gt;
        ///:TaskTo:
        ///&lt;/p&gt;.
        /// </summary>
        public static string HtmlTaskInfo {
            get {
                return ResourceManager.GetString("HtmlTaskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма данни.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставчик на електронни административни услуги: 
        ///:ElectronicServiceProvider:
        ///
        ///Уникален регистров идентификатор на получения документ: 
        ///:DocumentURI:
        ///
        ///Вид на пренос: 
        ///:TransportType:
        ///
        ///Заявител на електронната административна услуга:
        ///:Applicant:
        ///
        ///Подаден документ: 
        ///УРИ в регистъра на информационните обекти :DocumentTypeURI:, :DocumentTypeName:
        ///
        ///Извършил регистрацията: 
        ///:RegisteredBy:
        ///
        ///Информация за достъп до получения документ: 
        ///:CaseAccessIdentifier:
        ///
        ///Време на създаване на съобщението: 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReceiptAcknowledgedMessage {
            get {
                return ResourceManager.GetString("ReceiptAcknowledgedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сертифицирана система: :AISURI:.
        /// </summary>
        public static string ReceiptAcknowledgedMessageRegisteredByAISURI {
            get {
                return ResourceManager.GetString("ReceiptAcknowledgedMessageRegisteredByAISURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :PersonNames:, :AISUserIdentifier:.
        /// </summary>
        public static string ReceiptAcknowledgedMessageRegisteredByOfficer {
            get {
                return ResourceManager.GetString("ReceiptAcknowledgedMessageRegisteredByOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставчик на електронни административни услуги: 
        ///:ElectronicServiceProvider:
        ///
        ///Уникален регистров идентификатор на регистриран документ:
        ///:DocumentURI:::ElectronicServiceProvider: 
        ///
        ///Вид на пренос:
        ///:TransportType:
        ///
        ///Получаването не се потвърждава:
        ///:Discrepancies:
        ///
        ///Заявител на електронната административна услуга: 
        ///:Applicant:
        ///
        ///Подаден документ: 
        ///УРИ в регистъра на информационните обекти :DocumentTypeURI:, :DocumentTypeName:
        ///
        ///Време на създаване на съобщението: 
        ///:ReceiptTime:
        ///
        ///Електронен подпи [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReceiptNotAcknowledgedMessage {
            get {
                return ResourceManager.GetString("ReceiptNotAcknowledgedMessage", resourceCulture);
            }
        }
    }
}
